### ISSUE TITLE
canned etcd

### ISSUE THREAD

**Issue by gianarb** [testcontainers/testcontainers-go#101]
Lisa from Influx wrote this etcd container request for one of our tests. Probably we can make it to be a canned container as well.
```
	reqEtcd := ContainerRequest{
		Image: "quay.io/coreos/etcd:v3.2",
		WaitingFor: wait.ForAll(
			wait.ForLog("listening for client requests on 0.0.0.0:2379"),
		),
		ExposedPorts: []string{"2379/tcp", "4001/tcp"},
		SkipReaper:   true,
	}
```

**Comment by achew22** [comment]
Has there been any consideration of creating a text format that could be shared among the various testcontainers projects rather than having a disparate set for each library?

**Comment by mdelapenya** [comment]
We started this PR, which could be the seed for modules: https://github.com/testcontainers/testcontainers-go/pull/618

It creates examples to be consumed by the website, but turning them into modules would be a matter of adjusting the templates.
