### ISSUE TITLE
[Enhancement]: Kafka module

### ISSUE THREAD

**Issue by michielboekhoff** [testcontainers/testcontainers-go#1033]
### Proposal

testcontainers-java supports a built-in Kafka module, to allow users to manage Kafka without a lot of the boilerplate. Is this something you'd be willing to accept? If so, I'm more than willing to create a PR for it.

I suppose this might wait to wait for #1016.

**Comment by mdelapenya** [comment]
Hi @michielboekhoff thanks for opening this issue, I'm linking it to #636 which is the tracking issue for modules and example modules.

Would you be interested in contributing the module?

**Comment by mdelapenya** [comment]
> I suppose this might wait to wait for https://github.com/testcontainers/testcontainers-go/pull/1016.

Indeed, although we could live with not having all modules using the new module design, and change them in following releases of the library

**Comment by mdelapenya** [comment]
Reopening because of https://github.com/testcontainers/testcontainers-go/pull/1034#issuecomment-1714855027
