### ISSUE TITLE
[Enhancement]: Return the same MappedPort after the same container was Stoped and Started

### ISSUE THREAD

**Issue by MetalRex101** [testcontainers/testcontainers-go#1044]
###  Description

Right now, if I create a container, then call `MappedPort(ctx, "5672/tcp")` method, it will return me a random port. If I call it several times on the same container, result will be the same. **BUT** if I call `Stop()` on the container, then `Start()` on the container and then `MappedPort(ctx, "5672/tcp")` - it will return me a new mapped port.

### The question

Is there any chance, to get the same MappedPort after the same container was stopped and then started?

**Comment by mdelapenya** [comment]
Hi @MetalRex101 thanks for opening this proposal, although I have to say that it would be very difficult to implement as Docker itself behaves in the same you described.

```
$ docker run -d --name foo -p 80 nginx:latest
$ docker ps -a
CONTAINER ID   IMAGE          COMMAND                  CREATED         STATUS        PORTS                                     NAMES
354648f82546   nginx:latest   "/docker-entrypoint.…"   2 seconds ago   Up 1 second   0.0.0.0:62084->80/tcp, :::62084->80/tcp   foo
$ docker restart foo
$ docker ps -a
CONTAINER ID   IMAGE          COMMAND                  CREATED          STATUS         PORTS                                     NAMES
354648f82546   nginx:latest   "/docker-entrypoint.…"   15 seconds ago   Up 2 seconds   0.0.0.0:62148->80/tcp, :::62148->80/tcp   foo
```

Please take a look at the exposed ports: 62084 when the container was created and 62148 when it was restarted.

**Comment by MetalRex101** [comment]
Thank you for the quick reply! Then, I guess, the only way is to map some fixed port..

**Comment by mdelapenya** [comment]
> Thank you for the quick reply! Then, I guess, the only way is to map some fixed port..

But then you'll lose the reproducibility of the test. If you "reserve" a port for that container, what if you run tests in parallel consuming the container? They will fail because of port allocation.

I'd ask if you could extend your use case more, so that we can find the best strategy for it

**Comment by MetalRex101** [comment]
I have tests for a wrapper over Rabbit MQ library, which verify, that wrapper reconnects to the Rabbit MQ in case RMQ service was down for some time. The easiest way to emulate service down - stop docker container, where the server is running.

Of course, I need the same external port when docker container is up again.
Right now a solution with fixed port works. Of course, you are right, that it makes impossible to run tests in parallel, since docker container ports will conflict.

It is also possible to generate random port before a test and set it as container fixed port, but i don't see it as a problem right now.

Of course, if you have better and more elegant solution, I would be happy to discuss it.

Anyway thanks for your tips!

**Comment by mdelapenya** [comment]
I'd suggest calling the `MappedPort` function again once the container is restarted, in order to get the new port.

```golang
c, err := GenericContainer(ctx, GenericContainerRequest{
	ContainerRequest: req,
	Started:          true,
})
require.Nil(t, err)
require.NotNil(t, c)

port, err := c.MappedPort(ctx, "80/tcp")
require.Nil(t, err)
fmt.Println("nginx is listening on port", port.Port())
duration := 1 * time.Second
err = c.Stop(ctx, &duration)
require.Nil(t, err)

err = c.Start(ctx)
require.Nil(t, err)

port, err = c.MappedPort(ctx, "80/tcp")
require.Nil(t, err)
fmt.Println("nginx is listening on a different port", port.Port())
```

**Comment by MetalRex101** [comment]
@mdelapenya, that is exactly the problem =)

The thing is, that Rabbit MQ client is initiated with a port right after container is created and started the first time.
Client starts to consume a queue.
If there is a new port for Rabbit MQ, I will need to recreate the client, which is unwanted solution.
Wrapper is written the way it wills silently try to reconnect to the server

The purpose of the wrapper is to recreate consumer channel, if it was disconnected. Recreating all the client connection is another level solvation, which I would like to not implement.
