### ISSUE TITLE
[Bug]: postgres module not working locally

### ISSUE THREAD

**Issue by samlaf** [testcontainers/testcontainers-go#1080]
### Testcontainers version

0.19.0 and master branch

### Using the latest Testcontainers version?

Yes

### Host OS

macOS

### Host arch

ARM

### Go version

1.19.5

### Docker version

```shell
Client:
 Cloud integration: v1.0.31
 Version:           20.10.23
 API version:       1.41
 Go version:        go1.18.10
 Git commit:        7155243
 Built:             Thu Jan 19 17:35:19 2023
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.17.0 (99724)
 Engine:
  Version:          20.10.23
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.10
  Git commit:       6051f14
  Built:            Thu Jan 19 17:31:28 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.18
  GitCommit:        2456e983eb9e37e47538f59ea18f2043c9a73640
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Docker info

```shell
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.10.3)
  compose: Docker Compose (Docker Inc., v2.15.1)
  dev: Docker Dev Environments (Docker Inc., v0.1.0)
  extension: Manages Docker extensions (Docker Inc., v0.2.18)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.25.0)
  scout: Command line tool for Docker Scout (Docker Inc., v0.6.0)

Server:
 Containers: 14
  Running: 1
  Paused: 0
  Stopped: 13
 Images: 40
 Server Version: 20.10.23
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2456e983eb9e37e47538f59ea18f2043c9a73640
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.49-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 5
 Total Memory: 7.667GiB
 Name: docker-desktop
 ID: IL3H:2O43:M6UC:DUYI:CWU6:6WQ3:UXRR:VPST:VZK2:6YX4:3HXF:KD26
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false
```

### What happened?

Trying to use the postgres module following the [example](https://github.com/testcontainers/testcontainers-go/blob/7ae3f5ae950813ea3fe1b071f7a17012d222f2dd/docs/modules/postgres.md) doc. However getting an error on the two dependencies on testcontainers.
<img width="546" alt="image" src="https://user-images.githubusercontent.com/9342524/232937402-71fe3b41-85cb-427a-887d-2c365d1ab541.png">

I believe this is because `WithImage` and `WithWaitStrategy` are only in the master branch, and not in v0.19, but the postgres module hardcodes the [testcontainers-go import to v0.19](https://github.com/testcontainers/testcontainers-go/blob/7ae3f5ae950813ea3fe1b071f7a17012d222f2dd/modules/postgres/go.mod#L9). My guess is that this works for you guys only because of the [replace statement](https://github.com/testcontainers/testcontainers-go/blob/7ae3f5ae950813ea3fe1b071f7a17012d222f2dd/modules/postgres/go.mod#L59) which takes the local version of testcontainers-go instead of v0.19. However, when requiring the postgres modules, it automatically installs the v0.19.0 testcontainers-go:

<img width="735" alt="image" src="https://user-images.githubusercontent.com/9342524/232937705-fa0afa49-4b53-4abe-be62-ffb6959b8431.png">

Is there a way to fix this? Or is the only solution to wait for the next release?

**Comment by mdelapenya** [comment]
> My guess is that this works for you guys only because of the [replace statement](https://github.com/testcontainers/testcontainers-go/blob/7ae3f5ae950813ea3fe1b071f7a17012d222f2dd/modules/postgres/go.mod#L59) which takes the local version of testcontainers-go instead of v0.19. However, when requiring the postgres modules, it automatically installs the v0.19.0 testcontainers-go

That's correct @samlaf , and this is unfortunate for us because our current docs system does not allow us to display the latest release instead of main (https://github.com/testcontainers/testcontainers-go/issues/511), therefore the docs site presents everything that is still in dev but not released yet, as the postgres module. Ple

As a workaround, you could clone testcontainers-go and `replace` it in your project to that location. At the same time, we plan to release really soon 🙏

**Comment by samlaf** [comment]
Seems to work indeed, thank you. Can't wait for the release though :)
