### ISSUE TITLE
[Security]:  CVE Issues 

### ISSUE THREAD

**Issue by CandiedCode** [testcontainers/testcontainers-go#1082]
### Testcontainers version

0.19.0

### Using the latest Testcontainers version?

Yes

### Host OS

Linux

### Host arch

x86

### Go version

1.20

### Docker version

```shell
NA
```

### Docker info

```shell
NA
```

### What happened?

Dependabot flagged Security Issues
<img width="968" alt="Screenshot 2023-04-23 at 9 18 21 PM" src="https://user-images.githubusercontent.com/8380706/233885057-4da53730-ea2a-461f-a647-986e086117e7.png">

**Comment by mdelapenya** [comment]
Thanks for opening this issue @CandiedCode. I'm going to close it as the upcoming release is fixing the issues reported in there. You could check the recent dependabot updates to verify it.

Cheers!

**Comment by CandiedCode** [comment]
I see there are fixes, but that is for the downstream dependencies.  Dependabot doesn't point that test-containers has a release that will resolve this and based on your comment it looks like the release hasn't been published yet.

Is there a way to see when the next release will be? @mdelapenya
