### ISSUE TITLE
[Enhancement]: wait.ForHTTP should default to examining mapped ports instead of port 80

### ISSUE THREAD

**Issue by anuraaga** [testcontainers/testcontainers-go#1083]
### Proposal

Currently, `wait.ForHTTP` defaults to port 80

https://github.com/testcontainers/testcontainers-go/blob/main/wait/http.go#L44

This causes a lot of confusion if leaving out `WithPort` to specify a correct port, with a "can't find port" error that isn't very explanatory, and I think happens in many cases since a port of 80 is often not exposed in normal containers.

It would be great if it instead inspected the mapped ports to do the check when an explicit one is not satisfied. I believe this is how Java behaves.

Alternatively, I would have `ForHttp` accept two parameters, the path and port, making port a required parameter rather than hoping port 80 may work, I think it's quite rare.

**Comment by anuraaga** [comment]
Thanks @mdelapenya - if the change to inspect ports makes sense I can send a PR.

**Comment by mdelapenya** [comment]
> Thanks @mdelapenya - if the change to inspect ports makes sense I can send a PR.

Yes please! 🙏 Also add a link to the Java implementation in the PR, for reference
