### ISSUE TITLE
Allow Passing in Context as io.ReadCloser

### ISSUE THREAD

**Issue by ClaytonNorthey92** [testcontainers/testcontainers-go#110]
**Description**
As of now, when we allow a user to build and image from a Dockerfile, we only allow them to pass in the build context as a string, which is meant to be the path to the build context on their filesystem.  Then [we archive that directory before we send it to the Docker API, so it becomes a type that implements ReadCloser](https://github.com/testcontainers/testcontainers-go/blob/master/docker.go#L278)

I would like to allow the ability to use a [ReadCloser](https://golang.org/pkg/io/#ReadCloser) as the context in `FromDockerfile`.  This would allow consumers of our API to dynamically set files within the archive before sending it to the Docker API, and would be less implicit than what we do now.  However, I would like to also keep our current functionality because I like the abstraction.

**To Reproduce**
Not a bug. No reproduction steps.

**Expected behavior**
I am not sure what we want the API to look like, maybe:
```go
type FromDockerfile struct {
    Context string
    ContextArchive io.ReadCloser
    Dockerfile string
}
```
if the consumer sets both `Context` and `ContextArchive` we could return an error, specifying that you should only choose one or the other.

**Additional context**
this [conversation](https://testcontainers.slack.com/archives/CBWBNR76G/p1572263731000400) started this idea

**Comment by ClaytonNorthey92** [comment]
@gianarb @mdelapenya what do you guys think of this one?

**Comment by gianarb** [comment]
I like the idea @ClaytonNorthey92 and I think it is a well-known interface in Go, let's do it as you suggested! Can you also write a set of examples for both scenarios? 
Thanks

**Comment by ClaytonNorthey92** [comment]
Hey @gianarb thanks! Yes I will make sure I include both documentation and tests for both scenarios (by `Context` as a `string` and as an `io.ReadCloser`)
