### ISSUE TITLE
Feature: Allow Ability to View Logs from Failed-to-Start Container

### ISSUE THREAD

**Issue by ClaytonNorthey92** [testcontainers/testcontainers-go#118]
**Please Note**
~~I am not 100% sure that this is possible, but it would be useful for debugging.~~
based on this thread, this is possible https://testcontainers.slack.com/archives/CBWBNR76G/p1574767579003000

**Describe the bug**
When starting a container, you have the option to "wait" for something to occur to determine the container has "started".  For example you can [wait.ForLog](https://github.com/testcontainers/testcontainers-go/blob/master/wait/log.go#L66).  A problem is if the container doesn't "start" because what you were waiting for didn't occur, you may want to print the logs to see why it didn't occur (maybe there was an error, maybe you spelled something wrong in your `wait.ForLog` 😬 ).  The currently functionality is: if the container fails to start, the `io.ReadCloser` that the `.Logs` function returns is `nil`.

I would like to propose ~~, if possible,~~ that we allow the reading of logs from a container that failed to start due to a context timeout.  The Java port just added functionality for [checking if the reason for failure was due to context timeout](https://github.com/testcontainers/testcontainers-java/pull/1837)

I vote we:
* check the failure to start reason
  * if it is due to a context timeout, we include the logs from that container

**To Reproduce**
```go
ctx := context.Background()

req := ContainerRequest{
	Image: "alpine",

	// my container request will log out something unexpected, but I
	// may still want to know what it logged
	Cmd:        []string{"echo", "this is unexpected!"},
	WaitingFor: wait.ForLog("I expect this!").WithStartupTimeout(10 * time.Second),
}
c, err := GenericContainer(ctx, GenericContainerRequest{
	ContainerRequest: req,
	Started:          true,
})

// if the container failed to start because of a timeout waiting for the expected logs,
// there may still be value in whatever was in the logs of the failed container
if err != nil && err.Error() == "failed to start container: context deadline exceeded" {

	l, logErr := c.Logs(ctx)
	if logErr != nil {
		t.Error(err)
	}

	logBuf := new([]byte)
	// this will error due to the l being nil due to the container failing to start
	_, logErr = l.Read(*logBuf)
	if logErr != nil {
		t.Error(err)
	}

	t.Errorf("error starting container because the deadline exceeded, but here are the useful logs: %s", logBuf)
}

if err != nil {
	t.Error(err)
}
```

**Expected behavior**
I would expect the error `"error starting container because the deadline exceeded, but here are the useful logs: this is unexpected!"`

**Additional Context**
https://testcontainers.slack.com/archives/CBWBNR76G/p1574767579003000

**Comment by ClaytonNorthey92** [comment]
I would like to work on this one, if no one has an objection.

**Comment by nikolayk812** [comment]
@ClaytonNorthey92 what about viewing logs not only from the stopped container? In Java version, it was possible to redirect logs from a container to your test log output.

Also, I think this lib is very quiet in general. Not many things in the log on what is going on and what is the progress.

**Comment by ClaytonNorthey92** [comment]
> @ClaytonNorthey92 what about viewing logs not only from the stopped container? In Java version, it was possible to redirect logs from a container to your test log output.
> 
> Also, I think this lib is very quiet in general. Not many things in the log on what is going on and what is the progress.

@nikolayk812 
that is a good idea...do you think that should be part of this pull request or we should add another issue for that?

just to clarify: what you mentioned would be redirecting the containers' logs to stdout that is output from the `test` command?
