### ISSUE TITLE
[Enhancement]: Provide a possibility to use keep containers running

### ISSUE THREAD

**Issue by sesigl** [testcontainers/testcontainers-go#1191]
### Proposal

If container-startup is slow, frequent test runs pose difficulties. Hence, it's advantageous to maintain container operations throughout the testing process.

Currently, we utilize the `reuse` function and continuously execute one test in debug mode, eliminating the need for containers. Initiate your dev environment and existing containers will be employed, speeding up execution.

A more inherent support would be ideal.

Suggestion:

Permit setting of ryuk "kill" duration (RYUK_RECONNECTION_TIMEOUT). If set high, containers should terminate if idle for x minutes. This enables container cleanup and reuses the existing container for frequent tests. If inactive longer, they'll be cleaned, necessitating a lengthier startup.

Despite seeming feasible, I've found no mention in the docs or testcontainers-go's configuration API. I'm keen to contribute if implementation is needed. I'd appreciate your input and ensure I'm not overlooking anything.

Thanks in advance.

**Comment by mdelapenya** [comment]
@sesigl I think this PR resolves what you proposed in this issue: https://github.com/testcontainers/testcontainers-go/pull/1668

It was released in `v0.25.0` so I'd give it a try to any release above that (latest is `v0.33.0`).

If resolved, I'd close this issue. Wdyt?

**Comment by mdelapenya** [comment]
Closing this as per my comment above. Please reopen it if you consider it's not solved 🙏 

Thanks!
