### ISSUE TITLE
Go fmt is not failing Travis build

### ISSUE THREAD

**Issue by mdelapenya** [testcontainers/testcontainers-go#124]
Running `go fmt ./...` with current master (https://github.com/testcontainers/testcontainers-go/tree/0c6fcb48ff1cfa4d82a45b587e76b3588a4dc192) discovers a formatting problem in the `docker_test.go` file.

```shell
$  testcontainers-go git:(master) ✗ go fmt ./...   
docker_test.go
```

```diff
$  testcontainers-go git:(master) ✗ git diff docker_test.go 
──────────────────────────────────────────────────────────────────────────────────────────────────────────
 modified: docker_test.go
──────────────────────────────────────────────────────────────────────────────────────────────────────────
@ docker_test.go:928 @ func TestContainerCreationWithBindAndVolume(t *testing.T) {
            BindMounts:   map[string]string{absPath: "/hello.sh"},
            VolumeMounts: map[string]string{volumeName: "/data"},
            Cmd:          []string{"bash", "/hello.sh"},
-            WaitingFor: wait.ForLog("done"),
+            WaitingFor:   wait.ForLog("done"),
        },
        Started: true,
    })
```

I wonder if the Travis build should be failed in that case 🤔 I think so, as Go is very opinionated when talking about source code format.

To check that Travis is showing same information: https://travis-ci.org/testcontainers/testcontainers-go/builds/629696018#L370-L371

Thoughts?

**Comment by ClaytonNorthey92** [comment]
I agree with this, the builds should fail if `go fmt` was not run on the files

**Comment by mdelapenya** [comment]
Fixed!

![image](https://media.giphy.com/media/AvMJCeu1EMmhG/giphy.gif)
