### ISSUE TITLE
[Enhancement]: Expose the compose recreate options

### ISSUE THREAD

**Issue by rach-id** [testcontainers/testcontainers-go#1276]
### Proposal

Currently, the implementation uses by default the `"diverged"` recreate strategy for docker-compose setups, and doesn't provide a way to override that:
https://github.com/testcontainers/testcontainers-go/blob/bc15b1182459fe07caf0ba425fa7036f0772e078/modules/compose/compose_api.go#L194-L195

Does it make sense to also provide these as options?

The issue I am facing is when trying to start the compose setup incrementally, i.e. start a container, run some tests, start another container that uses the first one as a dependency and run some other tests. This gives me the following errors:

- if I specify the container dependencies as part of `RunServices (deps)`, it fails with `The container name "..." is already in use by container`
-  If I dont, I get the `no such service: ...` error

So, I guess if we have the `Recreate` and `RecreateDependencies` options exposed, that would help with this, and also allow for more flexible testing setups.

**Comment by mdelapenya** [comment]
Hey @SweeXordious thanks for opening this issue. I'm currently triaging the repo, focusing on compose stuff.

I think you could achieve if we exposed the `stackUpOptionFunc` and `stackUpOptions` types:

```go
import tccompose "github.com/testcontainers/testcontainers-go/modules/compose"
...

	recreateForceFn := func() tccompose.StackUpOption {
		// At this moment, the types are not exported: 
		// return tccompose.stackUpOptionFunc(func(o *tccompose.stackUpOptions) {
		return tccompose.StackUpOptionFunc(func(o *tccompose.StackUpOptions) {
			o.Recreate = api.RecreateForce
			o.RecreateDependencies = api.RecreateForce
		})
	}
```

Then you would be able to define your own recreation strategy.

I only need to think about the implications of exposing the type, as this module was added long time ago and I'm not that familiar with it as I'd like to.
