### ISSUE TITLE
Log progress on containers being started/waited/etc

### ISSUE THREAD

**Issue by nikolayk812** [testcontainers/testcontainers-go#136]
Log progress on containers being started/waited/etc

**Comment by nikolayk812** [comment]
Well, looks like pulling of an image happens before logging that container is being started. Need to be fixed.

**Comment by mdelapenya** [comment]
Hi @nikolayk812 I'm triaging this repository and found this outdated issue, sorry for the late response 😞.

Is it still of your interest adding logs to the pull-image step? If so, would you be willing to send a contribution?

Thanks for your time here

**Comment by mdelapenya** [comment]
BTW, I noticed this was already added in #137. I'm closing this issue as resolved.

Thanks!!
