### ISSUE TITLE
[Enhancement]: incomplete documentation for postgres example

### ISSUE THREAD

**Issue by ChristianSch** [testcontainers/testcontainers-go#1362]
### Proposal

Hi there,

As [the postgres docs](https://golang.testcontainers.org/modules/postgres/) are based on the https://github.com/testcontainers/testcontainers-go/blob/7ae3f5ae950813ea3fe1b071f7a17012d222f2dd/modules/postgres/postgres_test.go, it produces code which is unusable. It is not clear what `tt` is from the context. You can't really know it, as it's rest related. Any change this could get fixed up?

It should really be something along the lines of:
```go
	"github.com/testcontainers/testcontainers-go"
	testpg "github.com/testcontainers/testcontainers-go/modules/postgres"
	"github.com/testcontainers/testcontainers-go/wait"

	container, err := testpg.RunContainer(ctx,
		testcontainers.WithImage("docker.io/postgres:15.2-alpine"),
		testpg.WithDatabase("test"),
		testpg.WithUsername("test"),
		testpg.WithPassword("test"),
		testcontainers.WithWaitStrategy(
			wait.ForLog("database system is ready to accept connections").
				WithOccurrence(2).
				WithStartupTimeout(5*time.Second)),
	)
```

Instead of:

![image](https://github.com/testcontainers/testcontainers-go/assets/6138133/0d265806-cb7a-462f-be8c-30f78dcd3124)

In theory I'm up for submitting a patch, but I really don't want to meddle with tests and doc generation processes.

**Comment by mdelapenya** [comment]
Hi @ChristianSch , thanks for the issue report.

We are using a plugin to extract the test code from test files and put it into the markdown files, which is optimal to sync code and documentation. The downside of this is that the test code, as you pointed out, could have references to testing structures (in this case a table, or even the testing library).

We have this issue open: https://github.com/testcontainers/testcontainers-go/issues/611, and/but I'd like to also have Go examples, that end up in the pkg.dev documentation site.

Given we want to prioritise code snippets that don't get outdated, and are executed as real tests, I think it would be hard at the moment to unlink those code snippets from the test files.

**Comment by sanan-go** [comment]
I think for documentation exports, you might consider testable Examples (https://go.dev/blog/examples)
They are also tests, but more readable and complete as snipped. Would it be possible?

At some point, I was going to give up using the postgres module and go with generic container API.
I found this issue after 30 minutes of digging - searching for proper wait strategies from random sources.

**Comment by mdelapenya** [comment]
> I think for documentation exports, you might consider testable Examples (https://go.dev/blog/examples)
They are also tests, but more readable and complete as snipped. Would it be possible?

Exactly, it's in our plans: https://github.com/testcontainers/testcontainers-go/issues/1362#issuecomment-1662617075

> We have this issue open: https://github.com/testcontainers/testcontainers-go/issues/611, and/but I'd like to also have Go examples

Regarding your frustration on finding accurate docs

> I was going to give up using the postgres module

I'm really sorry about that, hopefully I can dedicate a full time-slot for fixing all code snippets from the docs, also improving the module generator code to force an module_example.go test file for the Go Examples.

**Comment by mdelapenya** [comment]
@sanan-go @ChristianSch we have added #1600, which will force new modules to include testable examples. Once merged, I'm going to do round of reviews to all modules migrating them to examples.

I'll close this issue once everything is migrated.

Thanks for your support!
