### ISSUE TITLE
[Bug]: Dead link in docs

### ISSUE THREAD

**Issue by wiegell** [testcontainers/testcontainers-go#1369]
### Testcontainers version

x

### Using the latest Testcontainers version?

Yes

### Host OS

x

### Host arch

x

### Go version

x

### Docker version

```shell
x
```

### Docker info

```shell
x
```

### What happened?

The github actions link is dead on this page: https://golang.testcontainers.org/system_requirements/

**Comment by mdelapenya** [comment]
Oh thanks for reporting this! I expected the HTML link rendered from the sourcecode but it did from the website which, after thinking more carefully about it, makes sense 🤦 

I'll fix it now!
