### ISSUE TITLE
Write an example for SQL wait strategy

### ISSUE THREAD

**Issue by gianarb** [testcontainers/testcontainers-go#142]
I would like to get an Example function for the wait for SQL strategy #122

**Comment by rajibmitra** [comment]
I will working on this @gianarb

**Comment by gianarb** [comment]
Thanks a lot!

**Comment by mdelapenya** [comment]
Let's close this one, as there are tests demonstrating its usage: https://github.com/testcontainers/testcontainers-go/blob/769d576b0b7768e30b27a43aac71dadac95a8452/e2e/container_test.go#L16

Please feel free to reopen if you need anything else from this issue.

Thanks!
