### ISSUE TITLE
Fails to build on windows after 0.1.0

### ISSUE THREAD

**Issue by mrg0lden** [testcontainers/testcontainers-go#143]
**Describe the bug**
After last release, I started getting this error
```
..\..\go\pkg\mod\github.com\docker\docker@v0.7.3-0.20190506211059-b20a14b54661\pkg\system\filesys_windows.go:111:24: cannot use uintptr(unsafe.Pointer(&sd[0])) (type uintptr) as type *"golang.org/x/sys/windows".SECURITY_DESCRIPTOR in assignment
```

**To Reproduce**
Just use last version `0.1.0` on windows

```
$ docker info
Client:
 Debug Mode: false

Server:
 Containers: 8
  Running: 1
  Paused: 0
  Stopped: 7
 Images: 9
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.943GiB
 Name: docker-desktop
 ID: TFV5:ZNWP:MAWZ:TZSM:VZNB:DTLZ:PYHL:ADND:4ZIS:YDWB:76H5:MCRM
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 40
  Goroutines: 55
  System Time: 2020-02-04T14:47:00.406826238Z
  EventsListeners: 3
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Additional context**
Windows 10 1909

**Comment by mrg0lden** [comment]
Managed to solve it by using master version 
`go get github.com\docker\docker@master`

Feel free to close it if you don't think it's worth an investigation.

**Comment by gianarb** [comment]
Hello @mrg0lden thank your for your issue because I am sure somebody will have the same issue.

Unfortunately `go mod` leaves to the developer who uses the library the ownership for the dependency it runs. So there is not much we can do about it and we have other similar issues in this repo.

I will close it, but please keep opening issues if you have dependency problem, we will make our best to fix them and the community will benefit from you to be so open! have a good day

**Comment by Ya3Sh** [comment]
I tried using `github.com\docker\docker@master` and started getting 

`..\github.com\docker\docker@v1.4.2-0.20200213004705-3af8d484b132\pkg\system\init_windows.go:21:21: undefined: osversion.Build`.

Any ideas how to get around the issue?

**Comment by mrg0lden** [comment]
@Ya3Sh It's probably because the latest commit of master has some errors. 

I use this one and it works as it should: 
`go get github.com/docker/docker@v1.4.2-0.20200203170920-46ec8731fbce`

**Comment by Ya3Sh** [comment]
No luck with that either.
`
$ go build ./...

#github.com/docker/docker/pkg/system

..\..\go\pkg\mod\github.com\docker\docker@v1.4.2-0.20200203170920-46ec8731fbce\pkg\system\init_windows.go:21:21: undefined: osversion.Build
`

**Comment by e-zhydzetski** [comment]
Try `replace github.com/Microsoft/hcsshim v0.8.6 => github.com/Microsoft/hcsshim v0.8.7`
