### ISSUE TITLE
golang.org/x/sys/windows".SECURITY_DESCRIPTOR

### ISSUE THREAD

**Issue by Ya3Sh** [testcontainers/testcontainers-go#152]
**Describe the bug**
Project fails to build on windows when I depend on testcontainers-go v0.2.0 with below error:
..\..\..\..\pkg\mod\github.com\docker\docker@v0.7.3-0.20190506211059-b20a14b54661\pkg\system\filesys_windows.go:111:24: cannot use uintptr(unsafe.Pointer(&sd[0])) (type uintptr) as type *"golang.org/x/sys/windows".SECURITY_DESCRIPTOR in assignment

**To Reproduce**
Can you write a unit test to reproduce your issue?

**Expected behavior**

**Additional context**
Tried replacing the docker/docker dependency with different versions. No luck.

**Comment by Ya3Sh** [comment]
Possibly dupe of https://github.com/testcontainers/testcontainers-go/issues/143

**Comment by Ya3Sh** [comment]
#143 resolution didn't work for me.

**Comment by ImVexed** [comment]
Fixed for me by pulling the latest version of docker `go get github.com/docker/docker@aa6a9891b09cce3d9004121294301a30d45d998d`
This seems to stem from the testcontainers using an old version of docker.

**Comment by tomqwpl** [comment]
Also seeing this. Will try and work out how to use the PR

**Comment by mdelapenya** [comment]
Seeing this behaviour here: https://github.com/testcontainers/testcontainers-go/runs/1384925491?check_suite_focus=true

**Comment by mdelapenya** [comment]
I've sent a PR here #235 running the tests in multiple OS: windows and linux (unfortunately, GH does not support Docker on mac)

At this moment, the error described in this issue is fixed

**Comment by mdelapenya** [comment]
Since we do run `go build` in Linux, Windows and Mac, I'd say this issue is no longer reproducible at least since [`v0.10.0`](https://github.com/testcontainers/testcontainers-go/releases/tag/v0.10.0).

Could you please double check with the latest version of tc-go? If still seeing the issue, please reopen so we can dig into the root cause. Thanks in advance!!
