### ISSUE TITLE
[Feature]: Support regex in ForLog wait strategy

### ISSUE THREAD

**Issue by pablochacin** [testcontainers/testcontainers-go#1541]
### Problem

Sometimes it is necessary to check for log entries whose context varies, but follow a known pattern. Presently, the ForLog wait strategy only allows checking for fixed text.

For example, in the context of the k3s module, it would be required fo wait for a message with the pattern `".*Node controller sync successful.*` that indicates the cluster is ready, instead of the fixed text used now (`"k3s is up and running"`). 

See  [discussion in this thread](https://testcontainers.slack.com/archives/CBWBNR76G/p1693217479360819?thread_ts=1692981129.009009&cid=CBWBNR76G)

### Solution

Add a wait strategy that uses a regex instead of a fixed text.

### Benefit

* More flexibility in the validations.
* Consistency with for example the [java](https://github.com/testcontainers/testcontainers-java/blob/main/core/src/main/java/org/testcontainers/containers/wait/strategy/LogMessageWaitStrategy.java) implementation.

### Alternatives

Implementing this wait outside the container creation, reading all the log (for example using a {LogConsumer](https://golang.testcontainers.org/features/follow_logs/)). 

### Would you like to help contributing this feature?

Yes

**Comment by mdelapenya** [comment]
We cpuld add the regex as a new fluent method `AsRegex()` to avoid breaking the existing behaviour. This method would take the log string and use it as a regex.

**Comment by mdelapenya** [comment]
@pablochacin there is a PR coming!
