### ISSUE TITLE
Add final check in CI to double check that environment is clean

### ISSUE THREAD

**Issue by gianarb** [testcontainers/testcontainers-go#158]
In some way I would like to know if at the end of the test suite we still have some containers running, this is to be sure that the cleanup process works

**Comment by ClaytonNorthey92** [comment]
Would it be a good idea to use the Go Docker client to do so?  [Here is a good example](https://godoc.org/github.com/docker/docker/client#hdr-Usage) to list running containers.

Would we want to perform any action if there are still running containers? I assume we would want to stop them?

**Comment by gianarb** [comment]
Yes, I think it sounds like a good idea, it can be a bah script that runs as the last check, it should fail if there are containers running yes.

**Comment by ClaytonNorthey92** [comment]
> Yes, I think it sounds like a good idea, it can be a bah script that runs as the last check, it should fail if there are containers running yes.

@gianarb do we need a bash script? I think we can perform this check in Go with the Go Docker Client, we might be able to run the check as part of our tests, the check could run after a suite has finished

**Comment by mdelapenya** [comment]
My two cents: if the only goal is to ensure that there are no running containers (or networks or volumes) after the test suite runs, I'd simply go with a shell script returning 1. Writing it in Go would mean to maintain it 🤔

**Comment by gianarb** [comment]
@ClaytonNorthey92 I think @mdelapenya got what I am thinking about. Just a small hack to be sure that we get 0 containers running

**Comment by ClaytonNorthey92** [comment]
okay makes sense to me 👍
