### ISSUE TITLE
Reusable containers

### ISSUE THREAD

**Issue by a-urth** [testcontainers/testcontainers-go#169]
Hi everyone. I've came across problem running multiple instances of the same container among couple of different tests. And in case its something resource heavy like elasticsearch it takes time to spawn, those so it kinda makes sense to reuse them if one of the containers is already running.

I found that such functionality was implemented into java version of the projects and quickly looking through documentation I haven't found anything similar here.

So is there any functionality to reuse containers or are there any plans to implement it?

https://github.com/testcontainers/testcontainers-java/pull/1781

**Comment by gianarb** [comment]
Hello! Thank you for opening this issue. We do not have a feature like that. But it is for sure implementable and something that we can do!

**Comment by cprepos** [comment]
@a-urth You can set up a container as a global var in the test, and use TestMain to start your containers before tests begin. They will be available to all tests. 

`
var container testcontainers.Container

//TestMain controls main for the tests and allows for setup and shutdown of tests
func TestMain(m *testing.M) {
	//Catching all panics to once again make sure that shutDown is successfully run
	defer func() {
		if r := recover(); r != nil {
			shutDown()
			testLogger.Err(nil, "Panic")
		}
	}()
	setup()
	code := m.Run()
	shutDown()
	os.Exit(code)
}

func setup(){
//start container here and it will be available to all tests
}
func shutDown(){
//Shut down containers
}
`

**Comment by Krishan-Sharma** [comment]
Above is a decent solution if you are looking to reuse containers within one run of tests, across all tests but it is not at parity with Java's reusable containers implementation since that spans across JVM shutdowns as well.

**Comment by fbiville** [comment]
Please correct me if I'm wrong, but that still limits reuse per package, or?
Is there a single global `TestMain` or one per package?

**Comment by mdelapenya** [comment]
Relates #439

**Comment by deepakyadav** [comment]
Seems to be implemented in https://github.com/testcontainers/testcontainers-go/pull/464
Can we get a release?

**Comment by mdelapenya** [comment]
> Can we get a release?

Hopefully the release will be made soon, I need to step back for a few days on vacations, and after that will work a great release. Sorry for the inconvenience

In the meantime, do you think you can add a replace entry in your go.mod file pointing to the main branch?

**Comment by mdelapenya** [comment]
Closing as #464 is merged, thanks!
