### ISSUE TITLE
[Bug]: Data Race accessing reaper instance for docker containers

### ISSUE THREAD

**Issue by davidsbond** [testcontainers/testcontainers-go#1691]
### Testcontainers version

0.24.1

### Using the latest Testcontainers version?

Yes

### Host OS

Linux

### Host arch

amd64

### Go version

1.21

### Docker version

```shell
24.0.6
```

### Docker info

```shell
This is running in github actions so I don't have access to it.
```

### What happened?

When using testcontainers with the `-race` flag enabled, a race is detected within the testcontainers package. It seems to be due to some code paths not using the `reaperMux` when accessing the session identifiers. For example here:

https://github.com/testcontainers/testcontainers-go/blob/main/docker.go#L881

### Relevant log output

```shell
WARNING: DATA RACE
Write at 0x000001a3cc50 by goroutine 17:
  github.com/testcontainers/testcontainers-go.reuseOrCreateReaper()
      /home/runner/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.24.1/reaper.go:155 +0x624

Previous read at 0x000001a3cc50 by goroutine 14:
  github.com/testcontainers/testcontainers-go.(*DockerProvider).CreateContainer()
      /home/runner/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.24.1/docker.go:881 +0xb34
```

**Comment by mdelapenya** [comment]
Oh, you are totally right! I introduced the race condition checking if the reaperInstance is nil 🤦 

I'll work on a fix ASAP. Thanks for reporting this.

Just to let you know, we are working on a draft document for an eventual v1 release, in which we'd like to refine all the bootstrapping of the library, in particular how config, reaper and test session is initialised. So it would be fixed at that time in a more proper manner. Nevertheless, I'll tackle this bug now.

**Comment by mdelapenya** [comment]
I can reproduce the bug with:

```shell
go test -timeout 600s -run ^Test_BuildImageWithContexts$ . -race -count=1 -v
```

I also have a working branch without that error.

**Comment by mdelapenya** [comment]
A PR fix has been sent, thanks for the report!
