### ISSUE TITLE
Change github.com/satori/go.uuid to github.com/gofrs/uuid

### ISSUE THREAD

**Issue by gunturaf** [testcontainers/testcontainers-go#172]
@gianarb is there any planned go mod dependency change from `github.com/satori/go.uuid` to `github.com/gofrs/uuid` or the one that Google maintains `github.com/google/uuid` ?

If you haven't read the rationale why this should be took into consideration:

> This project was originally forked from the github.com/satori/go.uuid repository after it appeared to be no longer maintained, while exhibiting critical flaws. We have decided to take over this project to ensure it receives regular maintenance for the benefit of the larger Go community.

[ excerpt from github.com/gofrs/uuid [readme file](https://github.com/gofrs/uuid/#project-history) .]

**Comment by gianarb** [comment]
Yep! Wil update it asap!
