### ISSUE TITLE
[Enhancement]: Add "Using Rancher Desktop" to the docs

### ISSUE THREAD

**Issue by udf2457** [testcontainers/testcontainers-go#1722]
### Proposal

It is possible to use `testcontainers` with Rancher Desktop, with VZ and without administrative credentials, and the docs should reflect this.

HT to @pdrosos https://github.com/rancher-sandbox/rancher-desktop/issues/2609#issuecomment-1738432949

Requirements are:

1. An up-to-date version of Rancher Desktop (there were some key fixes to make this work somewhere around v1.6)
2. Set VZ mode networking in Rancher Desktop (hence avoiding the need for giving Rancher sudo access)
3. Change the default Rancher Desktop engine from `containerd` to `dockerd (moby)`
4. Set the following env-vars:
```
export DOCKER_HOST=unix://$HOME/.rd/docker.sock
export TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE=/var/run/docker.sock
export TESTCONTAINERS_HOST_OVERRIDE=$(rdctl shell ip a show vznat | awk '/inet / {sub("/.*",""); print $2}')
```

**Comment by eddumelendez** [comment]
Hi @udf2457, In Testcontainers for Java we got [this PR](https://github.com/testcontainers/testcontainers-java/pull/7591). Do you mind submitting the one for Testcontainers for Go?

**Comment by udf2457** [comment]
Since you ask so nicely @eddumelendez :wink:  #1724 

Although I would pass comment that perhaps some of the documentation (such as this) could be centralised in order to avoid duplication of common topics (such as this ... since setting up Rancher Desktop on Mac for Java is no different than for Go :wink:).

**Comment by mdelapenya** [comment]
Closing because #1724 was already merged, thanks for your contributions!

**Comment by mdelapenya** [comment]
> Although I would pass comment that perhaps some of the documentation (such as this) could be centralised in order to avoid duplication of common topics (such as this ... since setting up Rancher Desktop on Mac for Java is no different than for Go 😉).

You are totally right, and we have an internal project to converge all docs to a central place. Unfortunately, we are not there yet.
