### ISSUE TITLE
[Feature]: Add MSSQLServer module

### ISSUE THREAD

**Issue by agosmou** [testcontainers/testcontainers-go#1789]
### Problem

There is no existing module for MSSQL for Go

### Solution

Adding module for MSSQL

### Benefit

Supports MSSQL out of the box

### Alternatives

Alternative would be to use generic containers

### Would you like to help contributing this feature?

Yes

**Comment by agosmou** [comment]
Hi! Yes, I joined the slack yesterday 👍🏽 

I'll get working on it soon! Thanks for the tip on the scaffolding - duly noted.

Use case is related to integration testing Go API with MS SQL Server database

**Comment by mdelapenya** [comment]
PTAL https://golang.testcontainers.org/modules/

**Comment by mdelapenya** [comment]
You probably want to take a look at this: https://github.com/BraspagDevelopers/testcontainers-canned/blob/master/sqlserver/sqlserver.go

**Comment by agosmou** [comment]
> You probably want to take a look at this: https://github.com/BraspagDevelopers/testcontainers-canned/blob/master/sqlserver/sqlserver.go

Interesting - looks like they were rolling their own for dotnet and Go.

Ill take a look and see how I can mesh this with scaffolding you provided above.

**Comment by agosmou** [comment]
Jumping into this, this week! I'll keep you posted @mdelapenya 😄
