### ISSUE TITLE
Why port not found?

### ISSUE THREAD

**Issue by softshipper** [testcontainers/testcontainers-go#183]
Hi all

I am trying to use https://github.com/testcontainers/testcontainers-go as follows: 

    func TestGitAutoTag(t *testing.T) {
    
    	path, err := os.Getwd()
    	assert.NoError(t, err, err)
    
    	fmt.Println(path)
    	data := fmt.Sprintf("%s%s", path, "/gogs/data")
    
    	fmt.Println(data)
    
    	//Start gogs container
    	ctx := context.Background()
    	req := testcontainer.ContainerRequest{
    		Image:        "gogs/gogs:0.11.91",
    		ExposedPorts: []string{"3000/tcp"},
    		WaitingFor:   wait.ForHTTP("/"),
    		BindMounts:   map[string]string{data: "/data"},
    		Name:         "gogs",
    	}
    
    	gogs, err := testcontainer.GenericContainer(ctx, testcontainer.GenericContainerRequest{
    		ContainerRequest: req,
    		Started:          true,
    	})
    
    	assert.NoError(t, err, err)
    
    
    	defer gogs.Terminate(ctx)
    
    }

and it shows: 

    TestGitAutoTag: auto_tagger_test.go:38: 
        	Error Trace:	auto_tagger_test.go:38
        	Error:      	Received unexpected error:
        	            	port not found
        	            	github.com/testcontainers/testcontainers-go.(*DockerContainer).MappedPort  

It should be alias to:

    docker run --rm -it -p 3000:3000 --name=gogs --mount type=bind,source=`pwd`/gogs/data,target=/data gogs/gogs

What am I doing wrong? 

Thanks

**Comment by gianarb** [comment]
Hello @softshipper 
thank you for reporting this bug. I am able to reproduce your issue and I think it is related to the `wait.ForHTTP` strategy.

In the meantime can you replace that with `WaitingFor:   wait.ForLog("Listen: http://0.0.0.0:3000")`, it should give you the same effect.

I have a few things to ask you for, your operating system and version. And information about the version of the library you are using

**Comment by softshipper** [comment]
It takes a long time(61.56s):

```
2020/04/20 14:41:45 Starting container id: 7579b1bb43b0 image: quay.io/testcontainers/ryuk:0.2.3
2020/04/20 14:41:46 Waiting for container id 7579b1bb43b0 image: quay.io/testcontainers/ryuk:0.2.3
2020/04/20 14:41:46 Container is ready id: 7579b1bb43b0 image: quay.io/testcontainers/ryuk:0.2.3
2020/04/20 14:41:46 Starting container id: fd311e02b8cd image: gogs/gogs:0.11.91
2020/04/20 14:41:46 Waiting for container id fd311e02b8cd image: gogs/gogs:0.11.91
2020/04/20 14:42:46 Container is ready id: fd311e02b8cd image: gogs/gogs:0.11.91
--- PASS: TestGitAutoTag (61.56s)
=== RUN   TestGitAutoTag/Last_commit_does_not_have_a_tag
    --- PASS: TestGitAutoTag/Last_commit_does_not_have_a_tag (0.00s)
=== RUN   TestGitAutoTag/Last_commit_already_be_tagged
    --- PASS: TestGitAutoTag/Last_commit_already_be_tagged (0.00s)
=== RUN   TestGitAutoTag/Repository_requires_password
    --- PASS: TestGitAutoTag/Repository_requires_password (0.00s)
=== RUN   TestGitAutoTag/Commit_message_does_not_contain_[MAJOR],_[MINOR],_[PATCH]
    --- PASS: TestGitAutoTag/Commit_message_does_not_contain_[MAJOR],_[MINOR],_[PATCH] (0.00s)
PASS

```
Why?

One more question, how to specify bind like: 
`--mount type=bind,source=`pwd`/gogs/data,target=/data`
I've tried 
```
	req := testcontainer.ContainerRequest{
		Image:        "gogs/gogs:0.11.91",
		ExposedPorts: []string{"3000/tcp"},
		WaitingFor:   wait.ForHTTP("/").WithPort("3000/tcp"),
		BindMounts:   map[string]string{data: "/data"},
		Name:         "gogs",
	}
``` 

But it does not work. I would like to create a test like: 
`docker run --rm -it -p 3000:3000 --name=gogs --mount type=bind,source=`pwd`/gogs/data,target=/data gogs/gogs
`  

Thanks
