### ISSUE TITLE
Why port not found?

### ISSUE THREAD

**Issue by softshipper** [testcontainers/testcontainers-go#185]
Hi all 

I am trying to use https://github.com/testcontainers/testcontainers-go as follows: 

    func TestGitAutoTag(t *testing.T) {
    
    	path, err := os.Getwd()
    	assert.NoError(t, err, err)
    
    	fmt.Println(path)
    	data := fmt.Sprintf("%s%s", path, "/gogs/data")
    
    	fmt.Println(data)
    
    	//Start gogs container
    	ctx := context.Background()
    	req := testcontainer.ContainerRequest{
    		Image:        "gogs/gogs:0.11.91",
    		ExposedPorts: []string{"3000/tcp"},
    		WaitingFor:   wait.ForHTTP("/"),
    		BindMounts:   map[string]string{data: "/data"},
    		Name:         "gogs",
    	}
    
    	gogs, err := testcontainer.GenericContainer(ctx, testcontainer.GenericContainerRequest{
    		ContainerRequest: req,
    		Started:          true,
    	})
    
    	assert.NoError(t, err, err)
    
    
    	defer gogs.Terminate(ctx)
    
    }

and it shows: 

    TestGitAutoTag: auto_tagger_test.go:38: 
        	Error Trace:	auto_tagger_test.go:38
        	Error:      	Received unexpected error:
        	            	port not found
        	            	github.com/testcontainers/testcontainers-go.(*DockerContainer).MappedPort  

It should be alias to:

    docker run --rm -it -p 3000:3000 --name=gogs --mount type=bind,source=`pwd`/gogs/data,target=/data gogs/gogs

What am I doing wrong? 

Thanks

**Comment by gianarb** [comment]
Hello!

This is a duplicate of https://github.com/testcontainers/testcontainers-go/issues/183#issuecomment-616454067

Can you verify it works for you and close this issue?
Thanks

**Comment by softshipper** [comment]
Sorry I did not see it. I will close it.
