### ISSUE TITLE
v0.6.0 github release is using v0.5.1 git tag

### ISSUE THREAD

**Issue by mdelapenya** [testcontainers/testcontainers-go#188]
I see the tags are not in sync, and maybe this could cause confusion in our users.

https://github.com/testcontainers/testcontainers-go/releases/tag/v0.5.1

Not sure if creating a `v0.6.0` git tag at the same point would be a feasible solution 🤔

**Comment by gianarb** [comment]
oh good catch. github is a bit broken for me now but as soon as it returns stable I will look at it!

**Comment by gianarb** [comment]
oh good catch. github is a bit broken for me now but as soon as it returns stable I will look at it!

**Comment by gianarb** [comment]
I do not want to change it because I don't know the implication with `gomod` and things like that, so the new one should be good. Gonna close it for now
