### ISSUE TITLE
[Bug]: ImageSubstitutor not applied to ryuk image

### ISSUE THREAD

**Issue by aloifolia** [testcontainers/testcontainers-go#1893]
### Testcontainers version

v0.26.0

### Using the latest Testcontainers version?

Yes

### Host OS

Linux

### Host arch

x86

### Go version

1.21

### Docker version

```shell
24.0.7 (dind + client)
```

### Docker info

```shell
24.0.7
```

### What happened?

When I use [image name substitution](https://golang.testcontainers.org/features/image_name_substitution/), the substitutor will not be applied to the ryuk image. Hence, I see logs like

```
Waiting for container id 4887f0360761 image: docker.io/testcontainers/ryuk:0.5.1.
```

Now, this looks like a bug. In an environment that requires you to use a private registry, you need to be able to adapt ryuk, as well. Or am I missing something?

My test code looks like this:

```go
type MyImageSubstitutor struct{}

func (s MyImageSubstitutor) Description() string {
	return "MyImageSubstitutor: prepending my.private.registry.com/"
}

func (s MyImageSubstitutor) Substitute(image string) (string, error) {
        # these lines will never appear for the ryuk image, just for user-defined images
	fmt.Println("############################")
	fmt.Println(image)

	prefix := "my.private.registry.com/"
	if !strings.Contains(image, prefix) {
		return prefix + image, nil
	}

	return image, nil
}

testcontainers.ContainerRequest{
        Image: "hashicorp/consul:latest," # this will be replaced, as expected
        ...
        ImageSubstitutors: []testcontainers.ImageSubstitutor{MyImageSubstitutor{}},
}
```

**Comment by mdelapenya** [comment]
Hey @aloifolia at the moment the image substitutor is not applied to the reaper.

I think we can implement as a feature request instead of a bug, probably supporting it at the properties level. Please see my follow-up comment in https://github.com/testcontainers/testcontainers-go/pull/1719:

>We can support setting custom substitutions in the testcontainers.properties file. Please see https://java.testcontainers.org/features/image_name_substitution/#automatically-modifying-docker-hub-image-names to check requirements.

**Comment by mdelapenya** [comment]
Hey @aloifolia would it be enough if you could define the Ryuk image at the properties level, like in Java https://java.testcontainers.org/features/configuration/#customizing-images?

I have a working branch to implement that.

**Comment by aloifolia** [comment]
The documentation mentions that the configuration via properties is deprecated. 

For this reason, I use the environment variable _TESTCONTAINERS_HUB_IMAGE_NAME_PREFIX_ which does the job equally well for me.

**Comment by mdelapenya** [comment]
Cool, thanks for your input. I'm currently providing support for `TESTCONTAINERS_HUB_IMAGE_NAME_PREFIX` in a consistent manner.

**Comment by hasnain003** [comment]
@aloifolia How did you set the environment variable `TESTCONTAINERS_HUB_IMAGE_NAME_PREFIX`. I am asking because when I tried to set the environment variable its always execute after Get Env call read() method in config.
