### ISSUE TITLE
[Enhancement]: reduce flakiness in CLickHouse tests

### ISSUE THREAD

**Issue by mdelapenya** [testcontainers/testcontainers-go#1898]
### Proposal

Current failure on tests: https://github.com/testcontainers/testcontainers-go/actions/runs/6749314222/job/18349567515
> clickhouse_test.go:214: 
          	Error Trace:	/home/runner/work/testcontainers-go/testcontainers-go/modules/clickhouse/clickhouse_test.go:214
          	Error:      	Received unexpected error:
          	            	[handshake] unexpected packet [72] from server
          	Test:       	TestClickHouseWithConfigFile/YAML_Config
      clickhouse_test.go:215: 
          	Error Trace:	/home/runner/work/testcontainers-go/testcontainers-go/modules/clickhouse/clickhouse_test.go:215
          	Error:      	"[]" should have 1 item(s), but has 0
          	Test:       	TestClickHouseWithConfigFile/YAML_Config

Probably improved with a retry 🤔

**Comment by rafiramadhana** [comment]
@mdelapenya can i work on this? thx
