### ISSUE TITLE
Implement database containers

### ISSUE THREAD

**Issue by mraerino** [testcontainers/testcontainers-go#19]
The java implementation of testcontainers provides useful preconfigured setups for certain databases.
They usually predefine an image and setup the special waiting strategy for that database.

This should be straight-forward for Go as well since there are many database clients around to do this.

I think I'll get started with a `postgres` setup.

**Comment by gianarb** [comment]
Yep, this looks like a great idea. Can you write down some code here to help me understand how you imagine interacting with the postgres utils? probably just  a fake test is enough

**Comment by gianarb** [comment]
Should we start packaging this kind of solutions in a subpackage? Maybe a directory called `canned`?

**Comment by fbiville** [comment]
I'd be happy to write a Neo4j integration.

**Comment by gianarb** [comment]
I am gonna this issue for now! As you can read in our documentation Golang is not really flexible when it comes to managing multiple modules in the same project and dependency management is still a pain.

https://golang.testcontainers.org/modules/

We decided to stay focused on the core library for now. If you decide to develop your module open a PR and link it in our documentation. We are happy to share it with the community but not to maintain it directly at this stage ❤️

**Comment by mdelapenya** [comment]
We started this PR, which could be the seed for modules: https://github.com/testcontainers/testcontainers-go/pull/618

It creates examples to be consumed by the website, but turning them into modules would be a matter of adjusting the templates.

**Comment by mdelapenya** [comment]
Given #618 has been merged, we created https://github.com/testcontainers/testcontainers-go/issues/636, where you can find how to contribute new modules :)
