### ISSUE TITLE
[Enhancement]: adding more customization capability to MongoDB module

### ISSUE THREAD

**Issue by ugrkm** [testcontainers/testcontainers-go#1908]
### Proposal

Currently, there is no functions in MongoDB module to add username and password to the container. (There is this capability for postgres https://github.com/testcontainers/testcontainers-go/blob/555cb764ee8dbd9b8ce54349d230a402aa439b8f/modules/postgres/postgres.go#L91C36-L91C73 )

If this seems useful, I would like to work on this.

**Comment by mdelapenya** [comment]
>If this seems useful, I would like to work on this.

That would be fantastic! Go for it 👏
