### ISSUE TITLE
Sql wait strategy does not use defaultStartupTimeout

### ISSUE THREAD

**Issue by mniak** [testcontainers/testcontainers-go#193]
**question/suggestion**

Hi, I was exploring the code and found that the wait strategies for Http, Port and Log all uses the `defaultStartupTimeout()` which is  60 seconds.

But the SQL wait strategy uses 10 seconds. 
Shouldn't it use the same default value?

**Comment by gianarb** [comment]
Yes good catch! Are you happy to get a PR to fix that?
Thanks

**Comment by mniak** [comment]
Yes, I can do that.
