### ISSUE TITLE
Add PollInterval to the waiters for sql, http and host_port

### ISSUE THREAD

**Issue by mniak** [testcontainers/testcontainers-go#197]
All of them uses 100 miliseconds, which is in most cases fine.
Although it wouldn't hurt to be able to change these intervals

If accepted, I can do the PR myself

**Comment by mniak** [comment]
The log waiter already has this property

**Comment by gianarb** [comment]
Thank you for your workaround consistency and for the fact that you double-check first!
I am on board! Feel free to open a PR!

**Comment by mniak** [comment]
Just FYI, I created a fix in PR #200
