### ISSUE TITLE
[Enhancement]: Reduce verbose log output

### ISSUE THREAD

**Issue by mfridman** [testcontainers/testcontainers-go#1984]
### Proposal

The default log output from this package is quite verbose. It would be ideal if the happy path (by default) logged as little as possible and reported only errors. And for those that do want verbose output, there could be a "verbose" flag or setting that could be enabled.

TL;DR - regardless if it's opt-in or opt-out, it'd be nice for this to be configurable.

---

1. I explicitly disabled this feature, no need for this output:

```
**********************************************************************************************
Ryuk has been disabled for the current execution. This can cause unexpected behavior in your environment.
More on this: https://golang.testcontainers.org/features/garbage_collector/
**********************************************************************************************
```

2. Not really interested in the Docker engine info:

```
2023/12/06 21:56:59 github.com/testcontainers/testcontainers-go - Connected to docker: 
  Server Version: 24.0.6
  API Version: 1.43
  Operating System: Docker Desktop
  Total Memory: 7944 MB
  Resolved Docker Host: unix:///var/run/docker.sock
  Resolved Docker Socket Path: /var/run/docker.sock
  Test SessionID: be5bcf090d5ac5b55046d7a35a670ab7341c71919218f6ee1e64ea4190322e69
  Test ProcessID: 469ede8f-9797-46fb-9ce8-eccb642a0d47
```

3. This is cute (hehe), but not strictly necessary:

```
2023/12/06 21:50:06 🐳 Creating container for image postgres:16-alpine
2023/12/06 21:50:06 ✅ Container created: f40dcefbd017
2023/12/06 21:50:06 🐳 Starting container: f40dcefbd017
2023/12/06 21:50:07 ✅ Container started: f40dcefbd017
2023/12/06 21:50:07 🚧 Waiting for container id f40dcefbd017 image: postgres:16-alpine. Waiting for: &{timeout:<nil> deadline:0xc0001a6e98 Strategies:[0xc0003b1a40]}

[...]

2023/12/06 22:15:03 🐳 Terminating container: f40dcefbd017
2023/12/06 22:15:03 🚫 Container terminated: f40dcefbd017
```

I added a custom logger, but it only suppressed items 2 and 3 above.

```go
type nopLogger struct{}

var _ testcontainers.Logging = nopLogger{}

func (nopLogger) Printf(string, ...interface{}) {}
```

**Comment by ntin90** [comment]
I work around by setting the global Logger of tescontainers to ioutils.NopWriter, as following:
```golang
testcontainers.Logger = log.New(&ioutils.NopWriter{}, "", 0)
```
However it is not documented in official doc and is not straightforward to figure it out. It's still worth to implement its own NopLogger.

**Comment by mfridman** [comment]
This only partially suppresses the output, there's still a "Ryuk has been disabled [...]" message that is a straight fmt print call: 

https://github.com/testcontainers/testcontainers-go/blob/83ae8bffad522fb375eacd8ae23ec8c702dc2093/internal/config/config.go#L50

**Comment by ar-sematell** [comment]
There are a lot of places calling internal "log" as well.
It needs reference of the Logger variable to other packages such as "wait"
[wait/host_port.go:139](https://github.com/testcontainers/testcontainers-go/blob/1889099c85a946a41304f50a4ad78c1dd4e0ca65/wait/host_port.go#L139)

**Comment by mdelapenya** [comment]
Hi folks, I'm tackling this issue as part of the revamp for an eventual `v1` release candidate for the library (please see https://github.com/testcontainers/testcontainers-go/tree/v1)

I like the idea of only adding the default logging hook if and only if the `-v` flag is passed. Apart from that, the idea is to create one single place for the library logger, so that it's possible to configure it once in the client code.

**Comment by webstradev** [comment]
I think it would be quite nice to reduce the amount of logs.

When I run my test suite and I want to see the actual failure message I have to scroll through a bunch of testcontainer status logs.
Would be nice if all of this is only there if you run with -v or something like that.
![image](https://github.com/testcontainers/testcontainers-go/assets/82543732/56982198-3cd5-4faa-8928-db4863901c7f)

**Comment by mdelapenya** [comment]
Hi folks, I submitted https://github.com/testcontainers/testcontainers-go/pull/2624, PLMK what you think.

Thanks!

**Comment by mfridman** [comment]
Thanks @mdelapenya, I'll give this a shot in some OSS projects I maintain over the next few weeks.

**Comment by mdelapenya** [comment]
@mfridman there is another PR that rollbacks the behavior described in this issue: [#3459](https://github.com/testcontainers/testcontainers-go/pull/3459)

I'd like you to comment in there if possible. I see the value in having the logs enabled by default, being possible to disable by a flag, as proposed by @strowk.

**Comment by mfridman** [comment]
Sure, I have no strong opinion. As long as users can override the global with `SetDefault`, I am somewhat indifferent to the default.

I believe it should still let me use `-v` for my tests and prevent info/warn-level logs from testcontainers.

Not entirely sure how things are implemented internally, but errors should always be printed regardless of what the user sets for "normal" logs.
