### ISSUE TITLE
Way to define HostIP (interface)

### ISSUE THREAD

**Issue by dimuls** [testcontainers/testcontainers-go#203]
Need a way to define on which host interface will be used. Now `HostIP=0.0.0.0`. For testing purposes we do not want to expose app on public interfaces. Need a way to define `HostIP=127.0.0.1`.

**Comment by gianarb** [comment]
Hello! Do you mind to detail a bit more what you are trying to do? Is this a docker daemon configuration or what?

**Comment by dimuls** [comment]
Haven't used `testcontainers-go` for months. As far as i remember it is docker container configuration. We were need to bind testing containers' ports on `127.0.0.1` not on `0.0.0.0`.

For example, we have web server which uses port 80. To test it we need to run docker with this web server and somehow expose this port 80. But we do not want to expose it on public net interface (using `0.0.0.0`) but only `127.0.0.1`.

If we draw an analogy with `docker run` command's `-p` flag: we need `-p 127.0.0.1:80:80` not just `80:80`.

So it will be nice if using `testcontainers-go` one may able to configure interface on which exposed ports will be binded.

**Comment by mdelapenya** [comment]
Hi @dimuls I found this issue interesting and kind of related to this discussion: https://github.com/testcontainers/testcontainers-go/discussions/590

With the 0.18.0 release, you are able to define 3 different modifiers at the ContainerRequest layer:
- Docker config: https://github.com/moby/moby/blob/master/api/types/container/config.go#L70
- Docker HostConfig: https://github.com/moby/moby/blob/master/api/types/container/hostconfig.go#L378
- Docker EndpointSettings: https://github.com/moby/moby/blob/master/api/types/network/network.go#L49

If your setup involves updating any of those types, then you'll be able to achieve with the modifiers: https://golang.testcontainers.org/features/creating_container/#advanced-settings

**Comment by mdelapenya** [comment]
I'm going to close this issue as stale, although please reopen it if you need anything from us 🙏 

Thanks!
