### ISSUE TITLE
Make entrypoint configurable

### ISSUE THREAD

**Issue by aklinkert** [testcontainers/testcontainers-go#208]
Hey there,

for images that do have an entrypoint configured in its Dockerfile it seems currently not possible to override it. As far as I understand the code the docker client does provide it, but testcontainers simply doesn't offer a way to pass through the value.

**Comment by gianarb** [comment]
Hello @aklinkert 
that's right, thank you for opening this.
Do you want to help with a PR? The change should be around here 

https://github.com/testcontainers/testcontainers-go/blob/93d54445e8e10a1963b638cd19d8ce533d6b01d1/container.go#L69-L90

Otherwise let me know somebody will pick it up

**Comment by aklinkert** [comment]
I'm gonna contribute this! 💪

**Comment by gianarb** [comment]
Btw our master unit test are not all working right now. We are working on it, but if you can add a test for that feature it will be nice :) 

Bonus point if you can reuse the Nginx image or one that we already use in our testsuite
Thanks a lot!

**Comment by aklinkert** [comment]
@gianarb I've opened the pull request. I reused the CMD test as you mentioned, WDYT?
