### ISSUE TITLE
Spec 2.0 domain language with java implementation folks

### ISSUE THREAD

**Issue by mraerino** [testcontainers/testcontainers-go#21]
The folks doing the java implementation are currently working on a 2.0 that will include several refactors and breaking API changes.

Since they are in a process of planning the updated API for their 2.0 this would be a great opportunity to work together with them to get a consistent domain language for all testcontainer implementations.

Also, ideas about waiting strategies and general docker handling could be discussed in unison.

This would make it easier for users of different languages to use testcontainers in a similar way.

**Comment by gianarb** [comment]
I think this can be closed, the new API should be in line right?

**Comment by mdelapenya** [comment]
There is a team effort where, in the long term, we'd like to create an homogeneous experience using any of the supported languages.

I'm closing this issue, but @mraerino please reopen it if you have any other concern or question. Thanks!
