### ISSUE TITLE
[Enhancement]:  Document WithWaitStrategy option

### ISSUE THREAD

**Issue by pablochacin** [testcontainers/testcontainers-go#2116]
### Proposal

The `WithWaitStrategy` option is not documented in the [wait strategies section](https://golang.testcontainers.org/features/wait/introduction/). It is only mentioned in the modules.

**Comment by pablochacin** [comment]
I found they are actually [documented](https://golang.testcontainers.org/modules/#containerrequest-options) in the modules section and also somehow these [common options ](https://github.com/testcontainers/testcontainers-go/blob/main/docs/features/common_functional_options.md)are included in each module's documentation.

Maybe the only problem is they are not indexed properly and do not appear in the search

![image](https://github.com/testcontainers/testcontainers-go/assets/720259/9f3c94cd-1d36-4572-aef3-fef5ab1d34e0)

**Comment by mdelapenya** [comment]
@pablochacin the `WithWaitStrategy` option is referenced for every container module, as you pointed out in https://github.com/testcontainers/testcontainers-go/issues/2116#issuecomment-1889717496.

I'm not sure if adding it to the features/wait page would come with confusion, as that is a generic place for explaining what wait strategy does, not explaining that a functional option exists for modules.

I know it's possible to manually call the functional option once you have the container request, but mixing up the two container types (generic and modules) would not be desired.

But once we have the new v1 API, where a `container.New(ctx, ...opts)` function would eventually appear, then for sure this options should be documented as a first citizen from the container configuration API.

Let's keep this issue open for that. Does it make sense to you?
