### ISSUE TITLE
Add Must methods for other database modules

### ISSUE THREAD

**Issue by mdelapenya** [testcontainers/testcontainers-go#2134]
Replicate what the CockroachDB module is doing with `MustConnectionString`, adding them to any database module.

              Thanks! Also, asking because I don't see this for other database modules

_Originally posted by @eddumelendez in https://github.com/testcontainers/testcontainers-go/pull/2131#discussion_r1462000993_

**Comment by bearrito** [comment]
@mdelapenya I haven't contributed to this project before, but I can take this. It looks fairly straightforward.

**Comment by mdelapenya** [comment]
Fantastic! Looking forward to it 😎

**Comment by bearrito** [comment]
This could be closed.
