### ISSUE TITLE
[Enhancement]: Support waiting for codes (Exit and HTTP) using integers besides the existing code matchers

### ISSUE THREAD

**Issue by mdelapenya** [testcontainers/testcontainers-go#2205]
### Proposal

The idea is to add som esugar on top of the existing code matchers:

Instead of this (example using the wait.ForExec strategy):
```golang
WithExitCodeMatcher(func(code int) bool {
	return code == 0
})
```

having this:
```golang
WithExitCode(0)
```

It will internally call the code matcher.

**Comment by bearrito** [comment]
Could be closed.

**Comment by mdelapenya** [comment]
Close as completed in #2342
