### ISSUE TITLE
TESTCONTAINERS_HOST_OVERRIDE is documented but not implemented

### ISSUE THREAD

**Issue by mdelapenya** [testcontainers/testcontainers-go#2209]
I'm running into similar issue. I'm following https://golang.testcontainers.org/system_requirements/ci/gitlab_ci/#example-using-docker-socket and so far it doesn't seem to work. Is the `TESTCONTAINERS_HOST_OVERRIDE` variable implemented?

_Originally posted by @arvenil in https://github.com/testcontainers/testcontainers-go/issues/1373#issuecomment-1938564264_

We should remove those references and update to the most updated ones.

**Comment by shotmk** [comment]
Documentation is pointing to a wrong `TESTCONTAINERS_HOST_OVERRIDE`.
`TC_HOST` should be used.
Documentation should be fixed.

**Comment by mdelapenya** [comment]
@shotmk thanks for adding context to the issue, would you like to contribute it? 🙏
