### ISSUE TITLE
[Enhancement] [k6]: Retrieve test script from a URL

### ISSUE THREAD

**Issue by mdelapenya** [testcontainers/testcontainers-go#2246]
### Proposal

E.g.
```go
k6.WithTestScript("https://raw.githubusercontent.com/weesvc/workbench/main/scripts/api-compliance.js"),
```

**Comment by bearrito** [comment]
I can grab this as well. Is the main change here that we are retrieving a remote resource rather than using a local test file?

**Comment by mdelapenya** [comment]
Yes, this is the exact use case. I'd add support for allowing basic auth in case users want to fetch a resource from a private repository

**Comment by mdelapenya** [comment]
Closing as completed
