### ISSUE TITLE
[Feature]: Restart and expose container on the same port

### ISSUE THREAD

**Issue by qazwsxedckll** [testcontainers/testcontainers-go#2271]
### Problem

Now, if I call Stop followed by Start, the endpoint port changes randomly. I know it is on purpose.

### Solution

Add some configs to set a fixed port to expose.

### Benefit

It is really helpful to simulate some dependecies restarts or the client losts connection.

### Alternatives

Using host networkmode is an alternative but it may cause port conflicts.

### Would you like to help contributing this feature?

No

**Comment by mdelapenya** [comment]
Hey @qazwsxedckll you can do that at the moment you put your fixed port in the container request struct:

```go
ExposedPorts:  []string{"8086:8086/tcp"}
```

That will lead to a container using that fixed port:
```shell
docker ps
CONTAINER ID   IMAGE                       COMMAND                  CREATED         STATUS         PORTS                                         NAMES
23031c93bf64   influxdb:1.8.10-alpine      "/entrypoint.sh infl…"   5 seconds ago   Up 4 seconds   0.0.0.0:8086->8086/tcp, :::8086->8086/tcp     tender_almeida
```

So if that works for you, I think we can close this one.

Thanks!

**Comment by mdelapenya** [comment]
There are concerns about fixing a port in tests, but we acknowledge there are exceptions :)
