### ISSUE TITLE
Allow capturing container exit code

### ISSUE THREAD

**Issue by vbrown608** [testcontainers/testcontainers-go#231]
I'm using this tool to test code that must run in a container, rather than to set up containerized dependencies for tests that run on the host. I'd like to await the container's exit and capture the exit code. Is it possible? It looks like something similar can be done by calling `Exec` on an already-running container, but I would ideally like to run the container `Command` directly.

Am I missing something? If not, would you be open to a PR? One way to do it without polluting the interface much could be to expose an `Inspect` function on the container and let consumers of this package poll like in `Exec`. Alternatively, something like `Container.AwaitExit() (int, error)` would fit my use case perfectly.

**Comment by gianarb** [comment]
This is a legit and [Executing a command](https://www.testcontainers.org/features/commands/) is what we should implement in Go.
