### ISSUE TITLE
consul: Update wait strategy

### ISSUE THREAD

**Issue by mdelapenya** [testcontainers/testcontainers-go#2335]
note this introduced a flake. The former example was waiting for the listen port (as are most ad-hoc usages on github). This passes before the api is ready failing tests. I think it should be reverted to what the example used:

```
		testcontainers.WithWaitStrategy(wait.ForListeningPort("8500/tcp")),
```

_Originally posted by @codefromthecrypt in https://github.com/testcontainers/testcontainers-go/pull/2194#discussion_r1516991862_

**Comment by codefromthecrypt** [comment]
https://github.com/testcontainers/testcontainers-go/pull/2336
