### ISSUE TITLE
Version 0.8.0 is using an old path of logrus

### ISSUE THREAD

**Issue by nestorbr** [testcontainers/testcontainers-go#238]
**Describe the bug**
Doing `go get github.com/testcontainers/testcontainers-go`  you get an error,  it is pointing to an old path of `logrus` 

`go: github.com/testcontainers/testcontainers-go upgrade => v0.8.0`
`go: finding module for package github.com/Sirupsen/logrus`
`go: finding module for package github.com/docker/docker/errdefs`
`go: found github.com/Sirupsen/logrus in github.com/Sirupsen/logrus v1.6.0`
`go: github.com/testcontainers/testcontainers-go imports`
`        github.com/docker/docker/pkg/archive imports`
`        github.com/Sirupsen/logrus: github.com/Sirupsen/logrus@v1.6.0: parsing go.mod:`
`        module declares its path as: github.com/sirupsen/logrus`
`                but was required as: github.com/Sirupsen/logrus`

**Comment by namco1992** [comment]
@nestorbr It's not really this lib's issue, it's the dependency of this lib. You may find this https://github.com/testcontainers/testcontainers-go/issues/127#issuecomment-570958635 helpful.

**Comment by robertscherbarth** [comment]
I have the same issue. Can you please make a new release for this fix?

**Comment by kernle32dll** [comment]
This should be fixed if https://github.com/testcontainers/testcontainers-go/pull/245 get merged
