### ISSUE TITLE
Opened PR: Wait Strategy for TestContainers Docker compose - Go

### ISSUE THREAD

**Issue by shashank-g172** [testcontainers/testcontainers-go#241]
Hi, 

 This is specific to a compose file starting up services. 

 I was wondering if there's a way to grab an individual service from the ones being started up in a compose file, and apply a wait strategy to it as we do with a normal genetic container startup. I'm finding that introducing a random sleep time within a test isn't necessarily the best way to wait for a container to be up. 

Thanks, 
Shashank

**Comment by mdelapenya** [comment]
Hi @shashank-g172, that could be a great enhancement, thanks for the suggestion. Are you willing to open a PR with the contribution?

**Comment by shashank-g172** [comment]
Sure, I'd be willing to open up a PR and help out. Can I re-use the wait strategy that comes out of the box with a single container startup and implement in compose.go?

**Comment by gianarb** [comment]
I think you should have a look at how it is currently implemented in Java:

https://www.testcontainers.org/modules/docker_compose/#waiting-for-startup-examples

and see if we can do something similar, I think it is important to design an API that re-use the wait strategy we already have yes!

Thanks a lot and let us know!

**Comment by shashank-g172** [comment]
Thank you. I will open up a PR. 

This is exciting stuff :)

**Comment by sanan-fataliyev** [comment]
Hi. @shashank-g172, are you working on it?

**Comment by shashank-g172** [comment]
@sanan-fataliyev , Yes I will be.

**Comment by shashank-g172** [comment]
@sanan-fataliyev  - Here's a quick update, I'm still testing it out locally to verify that I have the right path forward. I'm essentially exposing the services and the containers as a map and iterating through the wait strategies just like the Java client does:

https://github.com/testcontainers/testcontainers-java/blob/master/core/src/main/java/org/testcontainers/containers/DockerComposeContainer.java#L249

**Comment by shashank-g172** [comment]
@mdelapenya  @gianarb  @sanan-fataliyev - I've opened up the PR as a draft. It mirrors the Java SDK for TestContainers to apply the wait strategy. 

An issue that I'm seeing in Travis (not locally, since the Travis Docker image works fine and these tests do not fail)  is that the Docker Daemon version is mismatched between the operations I intend to perform vs what the current TestContainers library uses:

https://travis-ci.org/github/testcontainers/testcontainers-go/jobs/742314519

This appears to be the root cause: https://github.com/docker/cli/issues/2533

I've tried to export a docker environment to solve this issue in the Travis builds based on this suggestion: 

https://stackoverflow.com/questions/62079794/error-response-from-daemon-client-version-1-40-is-too-new-maximum-supported-ap

Please let me know what you think.

**Comment by mdelapenya** [comment]
I think this was implemented in https://github.com/testcontainers/testcontainers-go/pull/308

Please reopen if you have any other consideration 🙏
