### ISSUE TITLE
[Docs] Add kafka container example

### ISSUE THREAD

**Issue by franklinlindemberg** [testcontainers/testcontainers-go#246]
I was wondering if it would be possible to have some defined container images (similar to what we have for java testcontainers https://www.testcontainers.org/modules/kafka/).

I ported the kafka container to golang (https://github.com/franklinlindemberg/go-samples/blob/master/samples/testcontainer/kafkacluster.go) and if you think it makes sense, I could add it to this project so more people could reuse it.

What do you think?

**Comment by smallnest** [comment]
https://medium.com/trendyol-tech/kafka-test-containers-with-golang-b85e4b2469db is not completed and I have run it but failed.

Hope add a kafka example in this project.

**Comment by mdelapenya** [comment]
@franklinlindemberg we would like to start the discussion on module (formerly called `canned`) containers: https://github.com/testcontainers/testcontainers-go/discussions/509 (we converted the issue into a Discussion).

Would you be willing to participate in there? If so, can we close this issue and continue in the discussion thread? Thanks!

**Comment by franklinlindemberg** [comment]
@mdelapenya thanks for inviting me to the discussion, I'll be happy to contribute.

I'll close this one
