### ISSUE TITLE
[Enhancement]: define more errors as non-retryable during image pull

### ISSUE THREAD

**Issue by p-jahn** [testcontainers/testcontainers-go#2502]
### Proposal

If the docker client returns an error during image pull then the command is retried, except for [ErrNotFound](https://github.com/testcontainers/testcontainers-go/blob/main/docker.go#L1269).

There are more error types defined in https://github.com/moby/moby/blob/master/errdefs/defs.go that are also permanent, as far as I can tell.

I ran into the issue that, with invalid credentials, the pull was retried until I got temp blocked by the container registry. Pulling with invalid credentials should not be tried again.

Suggested errors to be seen as permanent/non-retryable:
* `ErrInvalidParameter`
* `ErrUnauthorized`
* `ErrForbidden`
* `ErrNotImplemented`

I'm unsure if all types might be returned by `ImagePull` (e.g. `ErrNotImplemented` seems unlikely). I also didn't check if there are similar places where the docker client is called within a retry mechanism. If so, it might be worth using a central definition that just contains all permanent types.

Happy to provide a PR if you like the suggestion.

**Comment by mdelapenya** [comment]
I like the idea of being more selective with the retries. Thanks for raising your concerns and opening the issue 🙇 

If you have to bandwidth for it, I'll be more than happy to review it
