### ISSUE TITLE
Document how to work with `failed to start container: context deadline exceeded`

### ISSUE THREAD

**Issue by cburgmer** [testcontainers/testcontainers-go#252]
**Describe the bug**
When upgrading the Postgres image past 10.6, I received a `failed to start container: context deadline exceeded`. This didn't help much, and running `docker ps` in parallel also did not show a container being brought up.

**To Reproduce**
```
	req := testcontainers.ContainerRequest{
		Image:        "postgres:10.6",
		ExposedPorts: []string{"5432/tcp"},
		Env:          map[string]string{"POSTGRES_DB": databaseName},
		WaitingFor: wait.ForSQL("5432", "postgres", func(port nat.Port) string {
			return database.DatabaseUrl(fmt.Sprintf("localhost:%s", port.Port()), password, databaseName)
		}),
		SkipReaper: true,
	}
```

**Expected behavior**
I'd love some help in the output to debug this.
What helped for me was the following:

```
$ docker ps -a
CONTAINER ID        IMAGE                        COMMAND                  CREATED              STATUS                        PORTS               NAMES
c36fde0217ad        postgres:10.14                   "docker-entrypoint.s…"   About a minute ago   Exited (137) 45 seconds ago                       laughing_cerf
$ docker logs c36fde0217ad
Error: Database is uninitialized and superuser password is not specified.
       You must specify POSTGRES_PASSWORD to a non-empty value for the
       superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run".

       You may also use "POSTGRES_HOST_AUTH_METHOD=trust" to allow all
       connections without a password. This is *not* recommended.

       See PostgreSQL documentation about "trust":
       https://www.postgresql.org/docs/current/auth-trust.html
```

**Comment by ikolomiyets** [comment]
I don't think it is an issue. By default, testcontainers are not concerned about the container logs. I.e. its aim is to bring the requested container to the running state. From this point of view it is equivalent to the docker's detached container start: all you can see is the container ID. And if it did not start you have to look explicitly into container's logs.

If you want to see the container logs when tests are running this could be achieved by creating a Log Consumer as described in [documentation](https://www.testcontainers.org/features/container_logs/).  

#250

**Comment by sazzer** [comment]
I think the big problem - both here and in #250 - is that the error displayed doesn't give any indication that the docker logs are useful. And actually, in some cases, by the time you want to look in those logs they've already gone.

On #250, the error gave the impression that testcontainers was trying to execute something inside the container that it couldn't. That was completely wrong, and led me down the wrong path for an hour or so.

Just updating the error message to include something like "Please inspect the docker container logs for container xyz" would have made a *huge* difference here.

Cheers

**Comment by ikolomiyets** [comment]
IMHO, pointing to the container logs when it fails to start could be misleading. 

There could be number of reasons why container failed to start. For instance, like in the snipped above when required environment variables were not set. Or there could be a scenario when WaitingFor property is set incorrectly in the container request. In the latter case logs would not help much.

**Comment by sazzer** [comment]
This is true. Maybe explicitly pointing to the logs isn't ideal, but
*something* could be done to make the error message better. In my case, I
spent ages thinking there was something wrong with the container, with
testcontainers itself, with my host environment, etc. And all the time,
looking at the container logs would have solved it in seconds.

In the case of WaitingFor being wrong, I wonder if that can somehow be
distinguished? The difference is that in my case the container failed to
start, in the other case it started but the code stops waiting too
early/late. But the obvious difference is - the container *is* running
still.

Cheers

**Comment by AWinterman** [comment]
I'm currently seeing an issue where the container fails to start within the context deadline, and am somewhat confused as to how to proceed. It starts fine locally but fails in ci...

**Comment by mdelapenya** [comment]
I agree with @ikolomiyets, pointing to the logs could lead to something else. It could be the Docker host configuration, the resources not being available... the `context deadline exceeded` comes from Go context and tells us that a timeout happened at some point of the container creation. 

>  By default, testcontainers are not concerned about the container logs. I.e. its aim is to bring the requested container to the running state. From this point of view it is equivalent to the docker's detached container start: all you can see is the container ID. And if it did not start you have to look explicitly into container's logs.

Exactly. `TC == docker run`. If it fails, you check the logs, the system, etc

Let me close this issue, as postgres should have been configured with the `POSTGRES_PASSWORD` variable (see my comment in https://github.com/testcontainers/testcontainers-go/issues/250#issuecomment-1131355860
