### ISSUE TITLE
[Enhancement]: Containerd support

### ISSUE THREAD

**Issue by eikenb** [testcontainers/testcontainers-go#2553]
### Proposal

I'd love to be able to use testcontainers to spin up containers in [Containerd](https://containerd.io/) for testing. Our platform is built directly on containerd.

I tried using Docker for the testcontainers as it uses containerd for the backend, but the containers weren't available via the containerd API (though the "moby" namespace was added). I am using somewhat older versions (docker.io 20.10.24, containerd 1.6.20) as our platform is Debian stable, so maybe this has been addressed in newer version. But native containerd support would still be preferable.

Thanks.

**Comment by kiview** [comment]
Hey @eikenb, how to you propose Testcontainers to interact with Containerd? All Testcontainers implementations interact with the container runtime through the Docker REST API. As to my knowledge, there is no REST API when using Containerd, so how would such an integration work?

With regards to the issue you have at hand, we generally suggest to use a remote Docker host in such situation (which can be configured by using `DOCKER_HOST`). Alternatively, we offer [Testcontainers Cloud](https://testcontainers.com/cloud/) as a ready-to-use remote Docker host for such use cases.

**Comment by kiview** [comment]
Just to clarify, you want to use Docker with `containerd` backend enabled, correct? This _should_ work, but we need to double check.

**Comment by mdelapenya** [comment]
@eikenb I'm closing this as per your comment. Thanks!
