### ISSUE TITLE
[Enhancement]: Allow network selection for modules (e.g. postgres)

### ISSUE THREAD

**Issue by tomek-kontakt** [testcontainers/testcontainers-go#2556]
### Proposal

**Motivation**
When a sidecar service, such as a cron job or processor, operates in conjunction with a database, we would like the ability to attach both the service and the database to the same network. Currently, this option appears to be available only for generic containers.

**Proposal**
Add another configuration option to options.go that enables setting the network (by name or by reference) and aliases. Alternatively, this feature could be introduced to selected modules as a module-specific configurer.

**Comment by mdelapenya** [comment]
Hi @tomek-kontakt thanks for reaching out. There are two functional options to configure the network, added in `v0.27.0`: https://golang.testcontainers.org/modules/postgres/#withnetwork

Is that what you need?

**Comment by mdelapenya** [comment]
Hi @tomek-kontakt I'm closing this as completed, as it's possible to attach module containers to networks using the options API.

Feel free to reopen if you consider it's not done yet.

Cheers!
