### ISSUE TITLE
[Bug]: TESTCONTAINERS_HOST_OVERRIDE is not working

### ISSUE THREAD

**Issue by emfomy** [testcontainers/testcontainers-go#2609]
### Testcontainers version

0.31.0

### Using the latest Testcontainers version?

Yes

### Host OS

N/A

### Host arch

N/A

### Go version

N/A

### Docker version

```shell
N/A
```

### Docker info

```shell
N/A
```

### What happened?

According to https://golang.testcontainers.org/system_requirements/rancher/ and https://golang.testcontainers.org/features/configuration/, we should be able to use `TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE` and `TESTCONTAINERS_HOST_OVERRIDE`.

However, these environment variables are not parsed in https://github.com/testcontainers/testcontainers-go/blob/v0.31.0/internal/config/config.go#L69

**Comment by mdelapenya** [comment]
Hi @emfomy thanks for opening this issue. Just to let you know, there is an ongoing PR addressing this: https://github.com/testcontainers/testcontainers-go/issues/2609

**Comment by stevenh** [comment]
This is fixed by two different pending PR's https://github.com/testcontainers/testcontainers-go/pull/2661 and https://github.com/testcontainers/testcontainers-go/pull/2725

**Comment by mdelapenya** [comment]
@emfomy could you verify if the current HEAD main resolved this issues? Thanks!

**Comment by emfomy** [comment]
It does solve the issue! Thanks!
