### ISSUE TITLE
[Bug]: Hosted API docs are already for the new API and don't match with the latest go package version 0.31.0

### ISSUE THREAD

**Issue by Glup3** [testcontainers/testcontainers-go#2625]
### Testcontainers version

0.31.0

### Using the latest Testcontainers version?

Yes

### Host OS

MacOS

### Host arch

ARM

### Go version

1.22.4

### Docker version

```shell
irrelevant
```

### Docker info

```shell
irrelevant
```

### What happened?

I have tried to implement the postgres module via the docs, but noticed they don't match with the latest pushed version (0.31.0). Will the package be updated soon? Should I wait for the new release or stick with 0.31.0, if so, are the older docs still available somewhere?

### Additional information

Also asked on Slack

**Comment by mdelapenya** [comment]
Indeed, that's an issue with our docs system, in which we do not support multiversion. It's unfortunate that the docs always show what's in main, even though the release has not been produced. We are planning to release really soon.

**Comment by mdelapenya** [comment]
@Glup3 please check #2627 The rendered version of the site after those changes will be https://deploy-preview-2627--testcontainers-go.netlify.app/modules/azurite/#run-function

I'd appreciate your feedback 🙏

**Comment by Glup3** [comment]
Thanks for the quick response! Would it be feasible to have the old usage examples as another tab also in the docs? Otherwise you have to dig into the library code in order to make it run and I don't really like that as a newbie 😅

**Comment by mdelapenya** [comment]
I'm afraid that would be more complex, as we replaced all the usages of the deprecated function with the new one.

**Comment by mdelapenya** [comment]
A new release will be eventually out soon. So you'll simply use the new version with the current docs 😄

**Comment by mdelapenya** [comment]
BTW you can find more about the versioning docs issue here: https://github.com/testcontainers/testcontainers-go/issues/511
