### ISSUE TITLE
[Bug]: Creation of DockerContainer results invalid state

### ISSUE THREAD

**Issue by stevenh** [testcontainers/testcontainers-go#2667]
### Testcontainers version

0.32.0

### Using the latest Testcontainers version?

Yes

### Host OS

N/A

### Host arch

N/A

### Go version

N/A

### Docker version

```shell
N/A
```

### Docker info

```shell
N/A
```

### What happened?

Containers created by compose module result in an invalid state due to private fields.

### Additional information

We should look at making all fields private and exposing constructors such as the currently private `containerFromDockerResponse`.

I tripped over this as I added an optimisation check using `isRunning` at the top of `Stop`, but this caused failures in `TestDockerComposeAPIWithStopServices` because the instance created wasn't fully initialised.

**Comment by mdelapenya** [comment]
> We should look at making all fields private and exposing constructors such as the currently private containerFromDockerResponse.

We could leverage the internal package, which is accessed by the compose module to have that constructor
