### ISSUE TITLE
"not enough arguments in call to p.client.ContainerCreate"

### ISSUE THREAD

**Issue by sazzer** [testcontainers/testcontainers-go#273]
Installing Testcontainers v0.9.0 currently fails to work, because Go is automatically pulling in Docker v20.10.1 instead of v17.12.0 and the API has changed.

As such, when I run anything I get:
```
/Users/sazzer/.gvm/pkgsets/go1.15.6/global/pkg/mod/github.com/testcontainers/testcontainers-go@v0.9.0/docker.go:645:39: not enough arguments in call to p.client.ContainerCreate
	have (context.Context, *container.Config, *container.HostConfig, *network.NetworkingConfig, string)
	want (context.Context, *container.Config, *container.HostConfig, *network.NetworkingConfig, *v1.Platform, string)
```

I can fix this by running:
```
$ go mod edit -require github.com/docker/docker@v17.12.0-ce-rc1.0.20200916142827-bd33bbf0497b+incompatible
```

But the next time I run `go get -u ./...` to update dependencies then it all breaks again.

**Comment by saminahbab** [comment]
I see this also

**Comment by buzzdan** [comment]
same here... any way to fix it ?

**Comment by buzzdan** [comment]
ok so i tried earlier versions too didnt work:
`$ go get -u github.com/testcontainers/testcontainers-go@v0.8.0`

output:
```
go: finding github.com/testcontainers/testcontainers-go v0.8.0
go: downloading github.com/testcontainers/testcontainers-go v0.8.0
go: extracting github.com/testcontainers/testcontainers-go v0.8.0
go: finding google.golang.org/genproto latest
go: finding golang.org/x/sync latest
go: finding golang.org/x/sys latest
go: finding github.com/containerd/continuity latest
go: finding golang.org/x/net latest
go: finding github.com/golang/groupcache latest
go: finding github.com/containerd/cgroups latest
# github.com/testcontainers/testcontainers-go
../go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.8.0/docker.go:614:39: not enough arguments in call to p.client.ContainerCreate
        have (context.Context, *container.Config, *container.HostConfig, *network.NetworkingConfig, string)
        want (context.Context, *container.Config, *container.HostConfig, *network.NetworkingConfig, *v1.Platform, string)
```

**Comment by gianarb** [comment]
Can you tell me which version of docker you have in your project? Thanks

**Comment by buzzdan** [comment]
@gianarb actually i dont use docker client in my project. go.mod file doesnt contain it if thats what you meant

**Comment by buzzdan** [comment]
after trying to `go get` test containers i see in my go.mod:

```
github.com/docker/docker v20.10.2+incompatible // indirect
```

**Comment by verigos** [comment]
> after trying to `go get` test containers i see in my go.mod:
> 
> ```
> github.com/docker/docker v20.10.2+incompatible // indirect
> ```
> 
> and on my machine docker version is:
> 
> ```
> $  docker --version
> Docker version 20.10.0, build 7287ab3
> ```

I also don't use docker in my project and have the same problem when trying to add `testcontainers-go` but a docker dependency was not added in my `go.mod`. Did you try removing the docker dependency? 

I had the same problem as everybody with `go get -u github.com/testcontainers/testcontainers-go`
I tried to run `go get -t -v ./...` everything was downloaded and `testcontainers-go` works ok now.

**Comment by sazzer** [comment]
The problem is that `github.com/testcontainers/testcontainers-go` is developed against the API from `github.com/docker/docker` v17.12.0. However, Go is pulling in v20.10.0 instead and that's got a breaking change in the API. In particular, at least one of the calls has had an extra parameter added to it that TestContainers isn't providing - because the version it's building against doesn't need it.

**Comment by buzzdan** [comment]
i see in `testcontainers-go` go.mod file the exact version+branch name?

https://github.com/testcontainers/testcontainers-go/blob/master/go.mod#L13

```
github.com/docker/docker v17.12.0-ce-rc1.0.20200916142827-bd33bbf0497b+incompatible
```

what does `+incompatible` means?

**Comment by derekperkins** [comment]
I'd vote for cutting a new release `v0.10` to work with the new Docker dependency.

**Comment by buzzdan** [comment]
@gianarb wdyt?

**Comment by gianarb** [comment]
I think @derekperkins is right!! Somebody has some time to draft a PR?! :)
Otherwise, I can do it this week

**Comment by buzzdan** [comment]
hi @gianarb !
is it ok to friendly ping you about it 🙏  ?

so sorry i dont have the ability for drafting a PR right now 🙏 
(meanwhile i use the hack @sazzer suggested)

**Comment by michielboekhoff** [comment]
@gianarb - I've created a PR that should close this: #283. If you could take a look at it when you get a chance, that'd be great.
