### ISSUE TITLE
Use testcontainers/ryuk instead of quay

### ISSUE THREAD

**Issue by Bablzz** [testcontainers/testcontainers-go#286]
Hello everyone!

How are you doing?

It's not a bug, just question

Can use [docker](https://hub.docker.com/r/testcontainers/ryuk) instead of [quay](quay.io/testcontainers/ryuk:0.2.3).

0.2.3 verson has got vulnerabilities and don't update for 2 years

Thanks in advance!

**Comment by gianarb** [comment]
Hey! Thank you for your question. When you build a new Container Request you can specify the reaper image you want to use:

https://github.com/testcontainers/testcontainers-go/blob/1e5e6e25edd168f92c50cb15ad53828580521540/container.go#L90

I think we should have a way to get configuration out from environment variables for example, but as far as today I don't know how to implement that in a way that is maintainable. But that solution works today I think!

**Comment by Bablzz** [comment]
Thanks for answering!
