### ISSUE TITLE
[Bug]: Bigquery: Timestamp is parsed as int but store as float

### ISSUE THREAD

**Issue by teamonafis** [testcontainers/testcontainers-go#2921]
### Testcontainers version

v0.32.0

### Using the latest Testcontainers version?

Yes

### Host OS

Mac

### Host arch

ARM

### Go version

1.22

### Docker version

```shell
Client:
 Cloud integration: v1.0.31
 Version:           23.0.5
 API version:       1.42
 Go version:        go1.19.8
 Git commit:        bc4487a
 Built:             Wed Apr 26 16:12:52 2023
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.19.0 (106363)
 Engine:
  Version:          23.0.5
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.8
  Git commit:       94d3ad6
  Built:            Wed Apr 26 16:17:14 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.20
  GitCommit:        2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc:
  Version:          1.1.5
  GitCommit:        v1.1.5-0-gf19387a
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Docker info

```shell
Client:
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     /Users/maeglin/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.17.3
    Path:     /Users/maeglin/.docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/maeglin/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.19
    Path:     /Users/maeglin/.docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.4
    Path:     /Users/maeglin/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/maeglin/.docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /Users/maeglin/.docker/cli-plugins/docker-scan
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  v0.10.0
    Path:     /Users/maeglin/.docker/cli-plugins/docker-scout

Server:
 Containers: 15
  Running: 1
  Paused: 0
  Stopped: 14
 Images: 24
 Server Version: 23.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc version: v1.1.5-0-gf19387a
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.49-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 5
 Total Memory: 7.667GiB
 Name: docker-desktop
 ID: b98efbe3-eb03-4369-8e98-02839377e3f2
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```

### What happened?

Hey all
I'am actually trying to write unit test usiging testcontainers-go and the bigquery emulator (see documentation [here](https://golang.testcontainers.org/modules/gcloud/)). 
Unfortunetely, I'm facing some issue regarding timestamp.
When using a GCP bigquery target (not using bigquery emulator), everything is going well. Using the emulator seems to generate an issue when parsing the timestamp value.

Here is playground (not building since it is timing out but I tested it locally)
https://go.dev/play/p/qWR3ESqZLkn

Here is the error I have
`panic: strconv.ParseInt: parsing "1734337137.930736": invalid syntax`

Does anyone already face this issue?

Regards

### Relevant log output

```shell
panic: strconv.ParseInt: parsing "1734337137.930736": invalid syntax
```

**Comment by mdelapenya** [comment]
HI @teamonafis I've tested your code locally, and I think the issue you're receiving is not related to testcontainers-go but to the emulator itself.

I verified that if you use a newer Docker image, such as `ghcr.io/goccy/bigquery-emulator:0.6.1`, the timestamp is correctly parsed. Maybe relates to https://github.com/goccy/bigquery-emulator/pull/276 (see their release notes: https://github.com/goccy/bigquery-emulator/releases/tag/v0.6.1)

I'm closing this one as not-related.

In any case, if you want to send a PR updating the examples with a more recent version of the emulator, please do it 🙏

**Comment by teamonafis** [comment]
Hi @mdelapenya , thanks for this quick reply. 
I will try with the latest version of the emulator, which is unfortunetely not available yet on my platform.
I just opened an issue [here](https://github.com/goccy/bigquery-emulator/issues/377).
I will kee everyone posted on this thread.

Cheers

**Comment by mdelapenya** [comment]
@teamonafis responded there that you can leverage the `--platform` flag. In your testcontainers-go code, you can achieve the same thanks to the `ContainerRequest.ImagePlatform` field.

**Comment by maeglindeveloper** [comment]
@mdelapenya , thank, that solved my issue and now everything is fine 🚀
