### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by jclavoie-jive** [testcontainers/testcontainers-go#293]
Hello! 

I'd like to first thank you for this testcontainers, we like it! 

I was wondering if there is any plan of cutting a release in the near future? The current version is broken with the latest docker engines and the update/changes have already been done in the master branch.

Thanks,

**Comment by gianarb** [comment]
here we are! https://github.com/testcontainers/testcontainers-go/releases/tag/v0.10.0

Thanks a lot @jclavoie-jive !
