### ISSUE TITLE
example from readme results in panic with older docker versions

### ISSUE THREAD

**Issue by kaxap** [testcontainers/testcontainers-go#300]
from README.md:
```go
	nginxC, err := testcontainers.GenericContainer(ctx, testcontainers.GenericContainerRequest{
		ContainerRequest: req,
		Started:          true,
	})
	if err != nil {
		t.Error(err)
	}
	defer nginxC.Terminate(ctx)
	ip, err := nginxC.Host(ctx)
```
if the call to `GenericContainer()` fails, then the error reported but test execution is continued until `ip, err := nginxC.Host(ctx)` where it results in panic due to nil pointer dereference. 
I think there should be `t.Fatalf("cannot create container: %s, check your docker version", err)` instead of `t.Error(err)`
to reduce possible confusion.

**Comment by gianarb** [comment]
Hey! Can you define old?

**Comment by kaxap** [comment]
I have upgraded my Docker right away. It is related to this particular [issue](https://github.com/testcontainers/testcontainers-go/issues/232#issuecomment-702330123) with Docker Desktop for Mac, as far as I remember.

**Comment by mdelapenya** [comment]
There is ongoing work to tractor the docs: #351 

I think we could close this one if that one is merged

**Comment by mdelapenya** [comment]
Let's close this issue, as it seems fixed by the Docker for Mac upgrade. Apart from that, in #353 the examples were updated
