### ISSUE TITLE
Wait strategies: use same WithStartupTimeout methods

### ISSUE THREAD

**Issue by mdelapenya** [testcontainers/testcontainers-go#314]
`sql.go` has a `Timeout` method, but the rest of the wait strategies have `WithStartupTimeout`. To avoid breaking changes, we could add the method and call it from the old one, including a deprecation message.

>Maybe the Strategy interface should force the method 🤔 

Besides that, it would be great if we add docs about the wait for strategies, same as in the Java project: https://www.testcontainers.org/features/startup_and_waits/

**Comment by mniak** [comment]
What about `WithTimeout`?
The `Startup` here is not needed since all wait strategies concern to startup.

**Comment by mniak** [comment]
What if we put the method `WithTimeout` on the `Strategy` interface?
It would ensure all valid that all wait strategies would have this method (even if they dont implement the timeout mechanism correctly).

It could be a problem if there were some situation where a timeout would not make sense. 
I can't think of one.

**Comment by mniak** [comment]
@mdelapenya please check the PR #322
