### ISSUE TITLE
How to control user account that launches images. 

### ISSUE THREAD

**Issue by naveenchlsn** [testcontainers/testcontainers-go#324]
We are seeing test containers throttled by dockerhub while downloading images. We have a docker hub pro account. Hence we were not expecting to get throttled by the docker hub. 

Which user does the test containers launch the dockers with? 
Is it possible to change it? 

Thanks,
Naveen

**Comment by gianarb** [comment]
Technically testcontains is just a wrapper around the docker/client. It depends on how you run tests. On its own, it relays on the process who starts the test suite.

I am wondering if we have to do something that we do not do to authenticate the docker/client 😕

**Comment by mdelapenya** [comment]
@naveenchlsn does https://github.com/testcontainers/testcontainers-go/issues/324#issuecomment-849426711 resolve your use case?

**Comment by mdelapenya** [comment]
@naveenchlsn I'm closing this issue as there is an open PR (#869) that provides a way to access the docker registry using the credential helpers.

Please reopen it if you do not see it resolved, thanks in advance for your support!
