### ISSUE TITLE
Start multiple containers at the same time

### ISSUE THREAD

**Issue by mniak** [testcontainers/testcontainers-go#332]
I propose a function like `tc.GenericContainer` but that would accept many container requests, and start them in parallel and return an array with the responses or a combined error.

Suggested signature
```
func GenericParallelContainers(ctx context.Context, reqs []GenericContainerRequest) ([]Container, error)
```

**Comment by mdelapenya** [comment]
This is a great request!! I'd like to know more about your specific use case, so that we could start the discussion/work.

I'm also interested in knowing if the docker compose implementation would work for you, and if not, the reasons for not using it.

Thank you in advance!

**Comment by mdelapenya** [comment]
Hey @mniak did you have the chance to read about the docker compose implementation? If that answered your question, then we would like to close this issue, thanks!
