### ISSUE TITLE
Feature request: Enable specifying query for `wait.ForSQL`.

### ISSUE THREAD

**Issue by sicoyle** [testcontainers/testcontainers-go#350]
It would be a nice feature if we could specify a query instead of being forced to use the default query of `SELECT 1` [here](https://github.com/testcontainers/testcontainers-go/blob/54854fb15ccb5162fe673bac4b2522e5f84de9a0/wait/sql.go#L75). It is stated that this repo helps with `integration/smoke tests` in the `README`, and I think this would help enable that better. With allowing users to specify what query to run, we could then wait for specific test data to propagate properly in the database before running test cases using only one wait strategy. This could potentially save people from having to specify a bunch of wait strategies for each specific service too (pending set up, number of services, project, use case, etc)!

**Comment by mdelapenya** [comment]
Yep, I think that would be doable and fairly simple. Are you willing to submit a PR? We can lead you there during the review process :)

**Comment by sicoyle** [comment]
Sure thing! Give me a few days, and I'll get something ready!
