### ISSUE TITLE
Update documentation to read from project perspective

### ISSUE THREAD

**Issue by jaredpetersen** [testcontainers/testcontainers-go#351]
There's a couple of sections in the documentation that reads as if this is something that only a single person works on:

_README.md_
> When I was working on a Zipkin PR I discovered a nice Java library called Testcontainers.
> It provides an easy and clean API over the go docker sdk to run, terminate and connect to containers in your tests.
> I found myself comfortable programmatically writing the containers I need to run an integration/smoke tests. So I started porting this library in Go.

_docs/features/creating_container.md_
> When I have to describe TestContainer I say: "it is a wrapper around the docker daemon designed for tests."

---
I think it would be more appropriate to update the language to take more of a project perspective rather than from a single person. Here's a sample rewrite of the opening passage of the README:
> Testcontainers-Go is a package that makes it simple to set up container-based dependencies for automated integration/smoke tests. The clean, easy-to-use API enables users to programmatically define containers that should be run as part of a test and clean up those resources when the test is done.

I'd be happy to put up a PR for this and other documentation-related issues. I think expanding the documentation and doing things like this would do a lot for the project.

PS -- I'd just like to say that I really appreciate the work that everyone has put in here. I'm a fan of Testcontainers on Java and was super happy to see that there was a Go equivalent. 🙂 

## Related Issues
- Closes #300

**Comment by mdelapenya** [comment]
I updated the description to include a section to auto close related issues

**Comment by mdelapenya** [comment]
I think we can close this issue, as #353 was merged, so that the docs use a project-style instead of a personal one.

Thanks for the work here!
