### ISSUE TITLE
Support arm64 architecture

### ISSUE THREAD

**Issue by samitpal** [testcontainers/testcontainers-go#352]
Looks like arm64 is not supported. Can that be supported please?

**Comment by mdelapenya** [comment]
Hey @samitpal, there is an ongoing PR to support pulling images in the right platform: https://github.com/testcontainers/testcontainers-go/pull/342 Is that we you mean or you have another use case in mind?

**Comment by samitpal** [comment]
yes @mdelapenya , i meant that. I will close this issue
