### ISSUE TITLE
Docker Compose V2: wait strategy cannot be applied: service not found

### ISSUE THREAD

**Issue by artamonovkirill** [testcontainers/testcontainers-go#374]
**Describe the bug**

While running with Docker Compose V2, compose tests with wait strategies like [TestDockerComposeWithWaitForService](https://github.com/testcontainers/testcontainers-go/blob/master/compose_test.go#L156-L179) from this repository:
```
=== RUN   TestDockerComposeWithWaitForService
Network a7b7aa95-7973-4113-b7d9-0b98c56e7557_default  Creating
Network a7b7aa95-7973-4113-b7d9-0b98c56e7557_default  Created
Container a7b7aa95-7973-4113-b7d9-0b98c56e7557-nginx-1  Creating
Container a7b7aa95-7973-4113-b7d9-0b98c56e7557-nginx-1  Created
Container a7b7aa95-7973-4113-b7d9-0b98c56e7557-nginx-1  Starting
Container a7b7aa95-7973-4113-b7d9-0b98c56e7557-nginx-1  Started
    compose_test.go:390: Failed when running []: one or more wait strategies could not be applied to the running containers: service with name nginx_1 not found in list of running containers
```

**To Reproduce**

Either:
* Run tests from this repo on Mac or Windows with [Docker Compose V2 enabled](https://docs.docker.com/compose/cli-command/#install-on-mac-and-windows)
* Run tests from this repo on Linux after [installing Docker Compose V2](https://docs.docker.com/compose/cli-command/#install-on-linux)
* Run tests on [this branch](https://github.com/artamonovkirill/testcontainers-go/tree/test/compose-v2)
    * Changed `docker-compose` to `docker compose`, see [the diff](https://github.com/testcontainers/testcontainers-go/compare/master...artamonovkirill:test/compose-v2?expand=1)
    * [Test results](https://github.com/artamonovkirill/testcontainers-go/runs/4251407429?check_suite_focus=true)

**Expected behavior**

Container startup is awaited.

**docker info**
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.3)
  compose: Docker Compose (Docker Inc., v2.0.0)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 10
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.47-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 1.942GiB
 Name: docker-desktop
 ID: 3JCN:ETYF:VD6H:3K6P:4STO:K6EI:CBF5:EIG3:SNN5:MFKI:OPIX:GSXA
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional Information:**
This is caused by a [breaking change](https://github.com/docker/compose/issues/229) in Docker Compose V2.

I tried installing Docker Compose V2 on `ubuntu-latest` nodes in GitHub Actions following [this instruction](https://docs.docker.com/compose/cli-command/#install-on-linux), but `docker-compose` was still V1.

**Workaround**
Prefix your compose `up` command with the `--compatibility` flag.

**Comment by mdelapenya** [comment]
Hey @artamonovkirill, thanks for opening this issue. Would you mind adding a scenario (code/snippet, project) where we could reproduce this issue? Thanks in advance!

**Comment by artamonovkirill** [comment]
Hi, @mdelapenya , as mentioned - it's for the [TestDockerComposeWithWaitForService](https://github.com/testcontainers/testcontainers-go/blob/master/compose_test.go#L156-L179) from this repo. I've added the link to my first comment, too.

I'll try to fork the repo and enable running the tests on MacOS later today (if GitHub actions support Docker for Mac).

**Comment by mdelapenya** [comment]
I'll give a try once a have certain bandwidth, thanks for the report!

**Comment by artamonovkirill** [comment]
Created https://github.com/testcontainers/testcontainers-go/pull/377

Running tests on a Mac will be a bit trickier:
* [Docker is not installed on Mac nodes](https://github.community/t/why-is-docker-not-installed-on-macos/17017)
* Depending on the architecture, tests like TestDockerComposeWithWaitLogStrategy would fails (if it's ARM)

**Comment by artamonovkirill** [comment]
Caused by https://github.com/docker/for-mac/issues/6035, but it looks like the issue is not occurring 100% of the time.

**Comment by artamonovkirill** [comment]
@mdelapenya updated the issue description (since it's not just Mac or Windows-specific, but rather Docker Compose V2 related).

**Comment by Malinskiy** [comment]
Unfortunately, this is not the full fix for the issue: short-running containers e.g. initialisation of some sort and wait strategy like `wait.ForExit()` in general might not have a container running during the wait strategy execution so the search for the container will fail unless an option for [All](https://github.com/moby/moby/blob/e60bddcc603f876e58021e69b81acba5b15305e7/api/types/client.go#L64) is specified in the docker query for `list`

To reproduce:
1. Use a service container that just does `echo Hello` and exits
2. Add a wait strategy for exitcode 0
3. Run the compose up

Could someone please reopen the issue?
