### ISSUE TITLE
Customise stdout and stderr for compose commands

### ISSUE THREAD

**Issue by byrnedo** [testcontainers/testcontainers-go#398]
Hi, 

I'd like to be able to send all the stdout or stderr for a compose `.Invoke()` to an  `io.Writer` of my choosing. Is there a way to do that currently?

**Comment by mdelapenya** [comment]
Hi @byrnedo, thanks for your question :) I'd say this is currently not possible (see https://github.com/testcontainers/testcontainers-go/blob/master/compose.go#L236-L237), although it could be considered a nice feature request if you explain your use case and possible implementations more in details (maybe here in this issue).

**Comment by mdelapenya** [comment]
Would this implementation satisfy your needs? #420

**Comment by edebernis** [comment]
Hey ! I found myself having the same need than @byrnedo.

Ideally, we should be able to pass options to the `LocalDockerCompose` struct to allow specifying custom pipes for command stdin, stdout and stderr.

Something like this:
```go
func WithStdinPipe(pipe io.Reader) DockerCompose
func WithStdoutPipe(pipe io.Writer) DockerCompose
func WithStderrPipe(pipe io.Writer) DockerCompose
```

Do you want me to implement a PR with this design ?

Thanks !

**Comment by mdelapenya** [comment]
@edebernis we merged https://github.com/testcontainers/testcontainers-go/pull/420. Is that enough for your use case?

**Comment by edebernis** [comment]
with #420, the command outputs are still piped to standards (stdout / stderr).

IMHO, it would be better to allow the user to override this behavior by specifing custom io.Writer / io.Reader to store command outputs.
And use stdout / stderr by default if nothing is specified.

**Comment by mdelapenya** [comment]
> with #420, the command outputs are still piped to standards (stdout / stderr).
> 
> IMHO, it would be better to allow the user to override this behavior by specifing custom io.Writer / io.Reader to store command outputs. And use stdout / stderr by default if nothing is specified.

We will be more than happy to review a PR :)

**Comment by mdelapenya** [comment]
Given this comment by @edebernis https://github.com/testcontainers/testcontainers-go/pull/470#issuecomment-1289608644, do you think we can close this issue?

**Comment by mdelapenya** [comment]
Closing as stale, please feel free to reopen if you need anything else from here.

Thanks!
