### ISSUE TITLE
Allow customization of docker.sock path

### ISSUE THREAD

**Issue by mniak** [testcontainers/testcontainers-go#399]
## Feature Request

I would like that the library understands an envbironment variable `TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE` and uses this when starting the reaper container (`ryuk`)

I'll try to contribute some code when I have some spare time
Something like this (using pseudo code on the change section):
on https://github.com/testcontainers/testcontainers-go/blob/9c3076fddb0ca14fceef5bb063690ef87aeeb346/reaper.go#L58-L69

```go
req := ContainerRequest{
    Image:        reaperImage(reaperImageName),
    ExposedPorts: []string{string(listeningPort)},
    Labels: map[string]string{
        TestcontainerLabel:         "true",
        TestcontainerLabelIsReaper: "true",
    },
    SkipReaper: true,
    // THIS ->
    Mounts:     Mounts(BindMount(
        strings.Coalesce(os.GetEnv("TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE"), "/var/run/docker.sock"),
        "/var/run/docker.sock",
    )),
    // <- THIS
    AutoRemove: true,
    WaitingFor: wait.ForListeningPort(listeningPort),
}
```

### Context
Following the announcement that [Docker Desktop is not free anymore](https://www.docker.com/blog/updating-product-subscriptions/) some users started using different tools to manage and their containers.

In some workaround scenarios the socket `docker.sock` is created in non-standard locations.
It's easy to setup the `DOCKER_HOST` environment variable and most applications that use the Docker API will run just fine.

But in [`testcontainers-go`](https://github.com/testcontainers/testcontainers-go/blob/9c3076fddb0ca14fceef5bb063690ef87aeeb346/reaper.go#L66) the reaper container, `ryuk` is [set-up to use the standard location](https://github.com/testcontainers/testcontainers-go/blob/9c3076fddb0ca14fceef5bb063690ef87aeeb346/reaper.go#L66).

Some tutorials [[#1]](https://blog.mornati.net/lima-vm-docker-desktop-alternative-for-macosx), [[#2]](https://zenn.dev/daiwahome/articles/4e90e1fb7d0954) suggest setting up the environment variable `TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE`, but according to my research, only [`testcontainers-java`](https://github.com/testcontainers/testcontainers-java/blob/205f21c242d067d67fc7f09d8d4738da28efcd08/core/src/main/java/org/testcontainers/DockerClientFactory.java#L157) and [`testcontainers-node`](https://github.com/testcontainers/testcontainers-node/blob/68e8cf9e31d8fc66530097ac101ac15fed897271/src/reaper.ts#L82) make use of these variables.

### Example
Mac users, for instance, can use [`lima-vm/lima`](https://github.com/lima-vm/lima) and install docker inside a virtual machine.
Most tutorials and sample config files create the socket on `/run/user/502/docker.sock` on the guest vm and a symlink at `$HOME/docker.sock` on the host computer.

**Comment by austince** [comment]
I've seen other examples that suggest using `TESTCONTAINERS_RYUK_DISABLED=true`, but that doesn't seem to be respected by this lib either, unless I'm mistaken.

**Comment by gianarb** [comment]
Right now we do not implement that but it will be great to cod something that behave like tc-java does 
https://www.testcontainers.org/features/configuration/
Thanks for opening this issue and for taking the time

**Comment by mniak** [comment]
PR: #407

**Comment by sneko** [comment]
In my case I try to use `testcontainers` in my CI/CD and to not mess with DinD (docker in docker) I try to use https://github.com/joyrex2001/kubedock (emulating Docker API to create the container on Kubernetes) but for this it requires disabling RYUK (since no real docker available).

As @austince I'm looking for a way to disable Ryuk through `TESTCONTAINERS_RYUK_DISABLED=true`.

Any published Docker image already by someone else? Just to try it out 😄 

Thank you,

**Comment by mdelapenya** [comment]
@mniak I think your initial issue with the variable was resolved in #407 and refactored in #414.

**Comment by mdelapenya** [comment]
> **EDIT:** I just realised that I can set `SkipReaper: true` in the `testcontainers.ContainerRequest` struct so Ryuk is disabled. But that's hardcoded in the code, there is no way to manage it through an environment variable.
> 
> I looked a bit more at the code and doing a PR for this is a bit annoying because which would prevail if both are set? Considering `TESTCONTAINERS_RYUK_DISABLED` for all containers whereas `SkipReaper` is per request. But since by default `SkipReaper` is not a pointer it's always considered as `false`. So to not make breaking change the only solution would be to say, whatever the `SkipReaper` specified, `TESTCONTAINERS_RYUK_DISABLED` will override.
> 
> In the meantime since my CI/CD had an environment variable `CI=true`, I set `SkipReaper` according to it.

@sneko what do you think if we start a discussion on how to redesign this part of the code, supporting a property/env-var to disable Ryuk at the configuration level (probably overridden at the containerRequest level)?

**Comment by mdelapenya** [comment]
I moved the settings configuration to a discussion (https://github.com/testcontainers/testcontainers-go/discussions/531)

I'm closing this issue, as the docker sock path it's now configurable, thanks!
