### ISSUE TITLE
Naming convention is different between docker-compose v1 and v2

### ISSUE THREAD

**Issue by karayel** [testcontainers/testcontainers-go#404]
**Describe the bug**
Container naming convention is different between Docker Compose versions v1 (Python) and v2 (Go).

```python 
def rename_to_tmp_name(self):
        """Rename the container to a hopefully unique temporary container name
        by prepending the short id.
        """
        if not self.name.startswith(self.short_id):
            self.client.rename(
                self.id, '{}_{}'.format(self.short_id, self.name)
            )
```
https://github.com/docker/compose/blob/5db8d86f127848367e4d721e992c188923c89d42/compose/container.py#L260

```go
// Separator is used for naming components
var Separator = "-"
```
https://github.com/docker/compose/blob/0062703bea796eca5b5f78a4779fa166cc18619c/pkg/compose/compose.go#L36

Need to update hardcoded separator in containerName
https://github.com/testcontainers/testcontainers-go/blob/8be67da6e9e105251d7b73f0fdbacc1f9d6f0b28/compose.go#L147

**To Reproduce**

https://gist.github.com/karayel/07ecb1c1651bd7430e795ccf1631a8a8

**INFO: You can reproduce this bug with using docker-compose v2**

**Expected behavior**
Match running docker container with given containerName

** docker info **
output of the command:

```
$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.7.1)
  compose: Docker Compose (Docker Inc., v2.2.3)
  scan: Docker Scan (Docker Inc., v0.16.0)

Server:
 Containers: 21
  Running: 0
  Paused: 0
  Stopped: 21
 Images: 6
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.94GiB
 Name: docker-desktop
 ID: X2TY:Y4ES:JJR6:WOCD:5ZPL:ACVO:DLZ6:QN3E:VWKW:LICR:TPZ5:NGNR
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional context**

I am happy to contribution after discussing the solutions to the problem.

**Comment by karayel** [comment]
As far as I can see, there are two pull request that solve this problem.

https://github.com/testcontainers/testcontainers-go/pull/377
https://github.com/testcontainers/testcontainers-go/pull/371

Is there any plan to merge this pull request ?

**Comment by seckinsen** [comment]
any update?

**Comment by Abdulsametileri** [comment]
@gianarb @mdelapenya @Bablzz @01101101M @jaredpetersen @franklinlindemberg up ??

**Comment by mdelapenya** [comment]
Hey, sorry for the delay, too much work on the day-to-day side.

I have a preference on https://github.com/testcontainers/testcontainers-go/pull/371, as it keeps backwards compatibility with previous docker-compose versions, but wanted to hear your voice.

**Comment by karayel** [comment]
Hey,

I think, #377 is more simple implementation than #371 and it keeps backwards compatibility

**Comment by mdelapenya** [comment]
> Hey,
> 
> I think, #377 is more simple implementation than #371 and it keeps backwards compatibility

Oh oh wait... you are right. I totally missed the combined filter in this second round of review. Thanks for focusing light to it.

Yeah, I rollback my "commit" and would consider #377 as the most feasible candidate

**Comment by karayel** [comment]
When can we merge #377 to master ? Is there any plan about release ?

**Comment by karayel** [comment]
Nice to hear that. Thanks @mdelapenya
