### ISSUE TITLE
Flaky test: TestContainerLogWithErrClosed

### ISSUE THREAD

**Issue by mdelapenya** [testcontainers/testcontainers-go#411]
I noticed this test is randomly failing. We'd need to further investigate why it fails and in which conditions. It may be written in a way that is not consistent, or maybe not up-to-date. Opening this issue for awareness.

```
=== RUN   TestContainerLogWithErrClosed
2022/02/28 16:27:00 Starting container id: 07de0af25f64 image: docker:dind
2022/02/28 16:27:00 Waiting for container id 07de0af25f64 image: docker:dind
2022/02/28 16:27:17 Container is ready id: 07de0af25f64 image: docker:dind
    logconsumer_test.go:210: port not found
--- FAIL: TestContainerLogWithErrClosed (20.54s)
```

**Comment by baez90** [comment]
I stumbled upon this issue while working on #414 I think it should be resolved in my PR by correctly using the [`PortEndpoint(ctx context.Context port nat.Port, proto string) (string, error)`](https://pkg.go.dev/github.com/testcontainers/testcontainers-go#DockerContainer.PortEndpoint) function

**Comment by mdelapenya** [comment]
Gotestsum support rerunning failed tests: https://github.com/gotestyourself/gotestsum#re-running-failed-tests

We could give it a try for adding stability to the pipeline meanwhile we investigate this flakiness
