### ISSUE TITLE
Allow insecure TLS in wait.HTTPStrategy

### ISSUE THREAD

**Issue by MeneDev** [testcontainers/testcontainers-go#45]
In Java insecure TLS connections can be allowed via JVM-Parameter. Other than that there seems to be no way to allow an insecure TLS connection. For go this is not an option. My current implementation adds `AllowInsecure` and `WithAllowInsecure` builder. However, I've asked @kiview if he knows more.

**Comment by gianarb** [comment]
is this not enough?

https://github.com/testcontainers/testcontainers-go/blob/master/wait/http.go#L66

**Comment by MeneDev** [comment]
No, this just enables tls, but the tls connection has to be secure, i.e. the certificates must validate (against the system certificate chain, as far as I know)

**Comment by MeneDev** [comment]
Something like this should be ok: https://github.com/MeneDev/testcontainers-go/blob/fd94801fb2b234a0092e555e89459b9e83be64ba/wait/http.go#L118

**Comment by MeneDev** [comment]
I've been quite busy the first quarter of this year but I hope I can soonish continue to contribute ;)
