### ISSUE TITLE
Rework wait.HostPortStrategy

### ISSUE THREAD

**Issue by MeneDev** [testcontainers/testcontainers-go#46]
The current version of HostPortStrategy doesn't work anymore. I'm not sure if I made a mistake when I initially implemented it or if the behavior of docker has changed.

Currently we're only looking for an opened exposed port, however docker opens the port right away even if the port is not opend inside the container. The java version runs various executions inside the container (like `docker exec`) to check if the port is opend in the container as well.

I would suggest to remove the current implementation completely, as it is misleading, and create a working version instead.

**Comment by gianarb** [comment]
Please feel free to remove it! Thanks @MeneDev !

**Comment by nikolayk812** [comment]
For me it looks that not only `LogStrategy` is affected as well. 
I try to run Postgres 

`func RunPostgres(database string) (string, error) {
	cport := "5432"
	user := "postgres"
	password := "password"

	ctx := context.Background()
	req := testcontainers.ContainerRequest{
		Image:        "postgres:9.6.14",
		ExposedPorts: []string{cport + "/tcp"},
		WaitingFor:   wait.ForLog("database system is ready to accept connections"),
		Env: map[string]string{
			"POSTGRES_USER":     user,
			"POSTGRES_PASSWORD": password,
			"POSTGRES_DB":       database,
		},
	}

	pg, err := testcontainers.GenericContainer(ctx, testcontainers.GenericContainerRequest{
		ContainerRequest: req,
		Started:          true,
	})
	if err != nil {
		return "", err
	}

	ip, err := pg.Host(ctx)
	if err != nil {
		return "", err
	}

	port, err := pg.MappedPort(ctx, nat.Port(cport))
	if err != nil {
		return "", err
	}

	url := fmt.Sprintf("postgres://%s:%s@%s:%s/%s?sslmode=disable",
		user, password, ip, port.Port(), database)

	return url, nil
}`

eventually I need to wait for 3 seconds after this call in order for test to pass.

I use sqlx to init connection
`
dbConn, err = sqlx.Connect("postgres", dbUrl)
`
and it fails with EOF if I wait for 2 seconds instead.

**Comment by gianarb** [comment]
Fixed #114
