### ISSUE TITLE
Please retag 0.0.1 as v0.0.1

### ISSUE THREAD

**Issue by VoyTechnology** [testcontainers/testcontainers-go#48]
Go mod is having problems parsing the current latest tag `0.0.1`, can this please be updated to use `v0.0.1` (`v` prefix)?

**Comment by VoyTechnology** [comment]
Oh, sorry, it is `0.0.1`. But the issue still holds. Will update the title.

**Comment by VoyTechnology** [comment]
Actually sorry. Bad day. It appears to work with `0.0.1` properly. Will close the issue.

**Comment by gianarb** [comment]
:+1: `go mod` scares me every time :I am glad it worked. Thanks!

**Comment by VoyTechnology** [comment]
It is possible that it is still failing, but I have a few more problems with the state of the packages in general. Basically every single time I change the dependency version to `0.0.1` `go get` reverts it back to `v0.0.0-20190108154635-47c0da630f72`. It might be an issue with some other dependency. I've seen something similar happen with https://github.com/SermoDigital/jose/releases, where it also defaults to commit. I am not sure is this an expected behavious.

I might reopen this issue after other upgrades. :)
