### ISSUE TITLE
Unable to use redis cluster on test containers

### ISSUE THREAD

**Issue by rohithm-angelone** [testcontainers/testcontainers-go#489]
**Describe the bug**
Create a redis cluster using https://github.com/Grokzen/docker-redis-cluster. Then when we try to connect to the cluster using go-redis, the cluster redirects to a different moved ip with default port of 7001, 7002 etc. But test containers doesn't allow to expose static ports so the request gets rejected and we cant use cluster redis in test containers

**To Reproduce**
req := testcontainers.ContainerRequest{
		Image:      "grokzen/redis-cluster:latest",
		SkipReaper: true,
		Env: map[string]string{
			"IP": "0.0.0.0",
		},
		ExposedPorts: []string{"7000/tcp", "7001/tcp", "7002/tcp", "7003/tcp", "7004/tcp", "7005/tcp"},
		WaitingFor:   wait.ForLog("Ready to accept connections"),
	}
create test container like this. try to connect to the redis on localhost and mapped port using go-redis ClusterClient and it fails

**Expected behavior**
Should be able to use the cluster redis without any issue.

**Additional context**

**Comment by mdelapenya** [comment]
Hi @rohithm-angelone I've been investigating about this issue and I'd like to start telling you I'm not a Redis expert.

I've been checking Redis docs about how to use the cluster in Docker, and found that they recommend special configurations for it, such as using the `host` network for that: 

- Go Redis Cluster docs: https://redis.uptrace.dev/guide/go-redis-cluster.html

```golang
rdb := redis.NewClusterClient(&redis.ClusterOptions{
    Addrs: []string{":7000", ":7001", ":7002", ":7003", ":7004", ":7005"},

    // To route commands by latency or randomly, enable one of the following.
    //RouteByLatency: true,
    //RouteRandomly: true,
})
```

- Redis Cluster and Docker: https://redis.io/docs/manual/scaling/#redis-cluster-and-docker

> Currently, Redis Cluster does not support NATted environments and in general environments where IP addresses or TCP ports are remapped.
>
>Docker uses a technique called port mapping: programs running inside Docker containers may be exposed with a different port compared to the one the program believes to be using. This is useful for running multiple containers using the same ports, at the same time, in the same server.
>
>To make Docker compatible with Redis Cluster, you need to use Docker's host networking mode. Please see the --net=host option in the [Docker documentation](https://docs.docker.com/engine/userguide/networking/dockernetworks/) for more information.

I gave it a try, combining both sources getting this, which fails to connect to the cluster:


```golang
package redis

import (
	"context"
	"fmt"
	"strings"
	"testing"

	"github.com/go-redis/redis/v8"
	"github.com/stretchr/testify/require"
	"github.com/testcontainers/testcontainers-go"
	"github.com/testcontainers/testcontainers-go/wait"
)

func TestRedis(t *testing.T) {
	ctx := context.Background()

	exposedPorts := []string{"7000/tcp", "7001/tcp", "7002/tcp", "7003/tcp", "7004/tcp", "7005/tcp"}

	req := testcontainers.ContainerRequest{
		Image: "docker.io/grokzen/redis-cluster:latest",
		Env: map[string]string{
			"IP": "0.0.0.0",
		},
		Networks:     []string{"host"},
		ExposedPorts: exposedPorts,
		WaitingFor:   wait.ForLog("Ready to accept connections"),
	}
	_, err := testcontainers.GenericContainer(ctx, testcontainers.GenericContainerRequest{
		ContainerRequest: req,
		Started:          true,
	})

	require.NoError(t, err)

	exposedAddrs := []string{}
	for _, exposedPort := range exposedPorts {
		exposedAddrs = append(exposedAddrs, fmt.Sprintf(":%s", strings.ReplaceAll(exposedPort, "/tcp", "")))
	}

	rdb := redis.NewClusterClient(&redis.ClusterOptions{
		Addrs: exposedAddrs,

		// To route commands by latency or randomly, enable one of the following.
		RouteByLatency: true,
		RouteRandomly:  true,
	})

	err = rdb.ForEachShard(ctx, func(ctx context.Context, shard *redis.Client) error {
		return shard.Ping(ctx).Err()
	})
	require.NoError(t, err)
}
```

I also checked not using the "host" network, exposing the ports and capturing their current endpoint:
```golang
package redis

import (
	"context"
	"strings"
	"testing"

	"github.com/docker/go-connections/nat"
	"github.com/go-redis/redis/v8"
	"github.com/stretchr/testify/require"
	"github.com/testcontainers/testcontainers-go"
	"github.com/testcontainers/testcontainers-go/wait"
)

func TestRedis(t *testing.T) {
	ctx := context.Background()

	exposedPorts := []string{"6379/tcp", "7000/tcp", "7001/tcp", "7002/tcp", "7003/tcp", "7004/tcp", "7005/tcp"}

	req := testcontainers.ContainerRequest{
		Image: "docker.io/grokzen/redis-cluster:latest",
		Env: map[string]string{
			"IP": "0.0.0.0",
		},
		ExposedPorts: exposedPorts,
		WaitingFor:   wait.ForLog("Ready to accept connections"),
	}
	container, err := testcontainers.GenericContainer(ctx, testcontainers.GenericContainerRequest{
		ContainerRequest: req,
		Started:          true,
	})

	require.NoError(t, err)

	exposedAddrs := []string{}
	for _, exposedPort := range exposedPorts {
		endpoint, err := container.PortEndpoint(ctx, nat.Port(exposedPort), "")
		require.NoError(t, err)

		exposedAddrs = append(exposedAddrs, strings.ReplaceAll(endpoint, "localhost", ""))
	}

	rdb := redis.NewClusterClient(&redis.ClusterOptions{
		Addrs: exposedAddrs,

		// To route commands by latency or randomly, enable one of the following.
		//RouteByLatency: true,
		//RouteRandomly: true,
	})

	err = rdb.ForEachShard(ctx, func(ctx context.Context, shard *redis.Client) error {
		return shard.Ping(ctx).Err()
	})
	require.NoError(t, err)
}

```

Could you let me know if, with this information, you would be able to continue your investigation on how to set up the Redis cluster for Docker? 

Thanks!
