### ISSUE TITLE
Blog announcement nit

### ISSUE THREAD

**Issue by nelz9999** [testcontainers/testcontainers-go#49]
Hello! I just read about your project via https://blog.gopheracademy.com/testcontainers-go/ ... I'm quite impressed and looking forward to possibly using it in the future.

I just wanted to point out a little nit in the example code in the blog post. In the AppA/AppB (or more specifically (Redis/AppB) example, when you spin up the `appB`, you seem to be re-using the `req` variable, which specifies the Redis container, rather than one specifying ApplicationB. (Which, for my selfish purposes, I was hoping was a locally-built executable... Maybe?)

**Comment by gianarb** [comment]
Hello! Thanks a lot for your heads up I will have a look at the example.
I don't really understand what you mean with locally built executable. Usually, testcontainers is used to sping up dependencies used to test your codebase, so you should not compile the app you are testing. You can just call the function in the test case itself

**Comment by nelz9999** [comment]
By "locally-built" I mean something that *I* produced... Rather than from a public package pulled down from Docker Hub.

From your example, I want "Application B" to be the API server that I made, so I can run API tests against it.

**Comment by gianarb** [comment]
I think this issue is not closed with this feature we have implemented:
https://github.com/testcontainers/testcontainers-go/blob/8f84b6f3af4c999830246d60b9bedd11dad59d0f/docs/features/build_from_dockerfile.md#build-from-dockerfile
