### ISSUE TITLE
[Enhancement]: improve the experience using log producers

### ISSUE THREAD

**Issue by mdelapenya** [testcontainers/testcontainers-go#525]
### Proposal

When needing to check logs for a container, we have to:
- define a log producer
- implement the accept function

This is fairly simple, but not very developer friendly.

We could provide a default log producer that outputs container logs to console, which is enabled/disabled in the container request, default true.

Then we would be able to see container logs at the moment they are produced.

We could start with a simple `LogProducer bool`, or an array of log producers for the case we want to send the logs to any other place, i.e. to elasticsearch 🤷

**Comment by mritunjaysharma394** [comment]
Is it still required yes, if yes then I would love to contribute to this, since I also needed it while debugging while I was adding k3s modules, I think this can be good feature to have
