### ISSUE TITLE
Rename the `wait/multi.go` file to `wait/all.go`:

### ISSUE THREAD

**Issue by mdelapenya** [testcontainers/testcontainers-go#537]
As discussed, we are going to rename the `multi.go` file to `all.go`:
- consistency with Java
- the exposed API is not changed (wait.ForAll)

_Originally posted by @mdelapenya in https://github.com/testcontainers/testcontainers-go/pull/536#discussion_r982250714_

**Comment by skofli** [comment]
Hey! I would like to work on this issue
