### ISSUE TITLE
Wait for specific console output

### ISSUE THREAD

**Issue by alde** [testcontainers/testcontainers-go#54]
It'd be great if it was possible to wait for specific log output, such as 

`MySQL init process done. Ready for start up.`

The port is available far in advance of this, causing me to have to add a `time.Sleep(30*time.Second)` in my test only to make sure it will have started.

**Comment by gianarb** [comment]
Thanks @alde good issue. This is in some way related to #19 .

This issue will be nice to have and it will involve a pre-feature that exposes an API to get/follow logs.

**Comment by gianarb** [comment]
As suggested via Slack https://github.com/testcontainers/testcontainers-java/blob/master/core/src/main/java/org/testcontainers/containers/wait/strategy/LogMessageWaitStrategy.java
