### ISSUE TITLE
Serve Kind (kubernetes)

### ISSUE THREAD

**Issue by gianarb** [testcontainers/testcontainers-go#56]
[kind](https://github.com/kubernetes-sigs/kind) is a Docker in Docker testing solution for Kubernetes. I think having a way to serve an "as a service" testing Kubernetes instance will be very helpful for who is writing Kubernetes integrations such as operator, CRD, SharedInformer.

**Comment by jlordiales** [comment]
@gianarb I thought Kind could be used as a regular lib, is that not the case? Haven't tried it myself so maybe it's not straightforward but I'm sure that was mentioned by it's authors as one of it's pros.

**Comment by gianarb** [comment]
You are right @jlordiales the idea here is to create a `canned` or `module` as called in testcontainers-java to make kind to work with the API we have in testcontainers.

https://github.com/testcontainers/testcontainers-go/pull/67

I have started here but I had to close it because I confused myself :D

if you have time and energy to try a different implementation let me kwno!

**Comment by jlordiales** [comment]
ah gotcha, haven't used the Java version so I was lacking that context. This is great btw! 👍

**Comment by Krishan-Sharma** [comment]
Hi @gianarb,

I would like to help with the implementation to use Kind for starting Kubernetes in a docker. Can you give me some context as to where we are with the implementation, challenges, design consideration, constraints that you have thought about while implementing this canned resource?

Also, some pointers on where to start would be greatly appreciated.

Thanks!

**Comment by anerathil** [comment]
Any news on that? :)

**Comment by gianarb** [comment]
Hello! unfortunately we decided to remove canned/modules as part of testcontainers for now. Because importing many libraries (kubernetes) in this case, will make dependencies a nightmare (they already are because of docker).

Submodules in Go are still something I don't know, so for now there is no place in this repository for such thing. But if you want to play in your own repo with a possible reusable Kind container we are happy to link it in our documentation https://golang.testcontainers.org/modules/
