### ISSUE TITLE
[Feature]: Allow build image from registries requiring authentication

### ISSUE THREAD

**Issue by paulozenida** [testcontainers/testcontainers-go#601]
### Problem

Currently, it is not possible to build a local Docker image that is built from another one that is fetching from a Docker registry that requires authentication

### Solution

Expose AuthConfig when creating docker requests so that clients may configure the necessary credentials.

### Benefit

It will allow to build Docker images that rely on other Docker images located in registries that require authentication

### Alternatives

Not applicable. I tried using `~/.docker/config.json` but I failed to do make it work.

### Would you like to help contributing this feature?

Yes

**Comment by mdelapenya** [comment]
Closed as already implemented, thanks!
