### ISSUE TITLE
[Enhancement]: Support Docker over SSH

### ISSUE THREAD

**Issue by phumberdroz** [testcontainers/testcontainers-go#614]
### Proposal

Docker can be used via SSH (DOCKER_HOST=ssh://user@host) 

Being able to run testcontainers on a remote host has a lot of benefits for example avoiding running heavy containers on the local machine or not having docker installed at all locally.

I worked on some initial support for this here: https://github.com/testcontainers/testcontainers-go/compare/main...phumberdroz:testcontainers-go:docker-over-ssh

It is currently blocked by a bug: https://github.com/docker/compose/issues/9448

I am creating this issue mainly to share this and if the Pull request is welcome I will contribute it as soon as it is possible. (There might be the need to upgrade docker compose pkg through)

**Comment by mdelapenya** [comment]
Hi @phumberdroz , thanks for opening this issue, which it's very similar to what the Java folks already answered here: https://github.com/testcontainers/testcontainers-java/pull/5039.

I recommend you reading it for more context on why we did not allow it for the Java project, which makes us not consider it doable for Go.

Please let us know what you think about it before eventually closing it.

**Comment by mdelapenya** [comment]
Closing this issue, as discussed in the Java thread. Please reopen it if you need more from us here.

Thanks!
