### ISSUE TITLE
[Bug]: testcontainers.NewDockerCompose() is not included in the latest release

### ISSUE THREAD

**Issue by andyautida14** [testcontainers/testcontainers-go#619]
### Testcontainers version

0.15.0

### Using the latest Testcontainers version?

Yes

### Host OS

MacOS

### Host arch

x86

### Go version

1.19

### Docker version

```shell
20.10.10
```

### Docker info

```shell
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.3)
  compose: Docker Compose (Docker Inc., v2.1.1)
  scan: Docker Scan (Docker Inc., 0.9.0)

Server:
 Containers: 20
  Running: 0
  Paused: 0
  Stopped: 20
 Images: 34
 Server Version: 20.10.10
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 5b46e404f6b9f661a205e28d59c982d3634148f8
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.47-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 1.939GiB
 Name: docker-desktop
 ID: SBAI:Y2QC:CJK6:5S2X:N7VS:QZQP:QCZU:JXHU:NPNR:CKNF:JJRR:WOEO
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### What happened?

I tried using `testcontainers.NewDockerCompose()` as documented from https://golang.testcontainers.org/features/docker_compose/, but it's failing because it cannot find the function (see the relevant log output section).

After a lot of head-scratching, I found that the changes that includes `testcontainers.NewDockerCompose()` is not included in version 0.15.0 here: https://github.com/testcontainers/testcontainers-go/blob/4c04bdf03605f862f9e0fc0e3b6d49a2ef02f744/compose.go

It's confusing because I thought it's already supported on the latest release.

### Relevant log output

```shell
test/pay_test.go:64:21: undefined: testcontainers.NewDockerCompose
test/pay_test.go:71:14: undefined: testcontainers.Wait
test/pay_test.go:93:42: undefined: testcontainers.ComposeStack
test/pay_test.go:143:42: undefined: testcontainers.ComposeStack
test/pay_test.go:144:29: undefined: testcontainers.RemoveOrphans
test/pay_test.go:144:53: undefined: testcontainers.RemoveImagesLocal
```

**Comment by mdelapenya** [comment]
Indeed, the docs apply to the latest version of the code in the main branch. Maybe worth it to add it explicitly in the docs.

We are rethinking the release/publication process to avoid this mismatched expectation (cc/ @kiview) 

Thanks for opening the issue, we'll use it to improve the library.

**Comment by kiview** [comment]
This situation currently holds true for all Testcontainers documentation variants that are published through our `mkdocs` system (and hosted at *.testcontainers.org).

**Comment by mdelapenya** [comment]
@andyautida14 I'm closing this issue, as we explained the reasons why DockerCompose was not in the latest release at the time of this posting (v0.15.0). 

Now that 0.16.0 is out, I think we can close it, but feel free to reopen or comment if needed, thanks!
