### ISSUE TITLE
[Enhancement]: Remove created volumes on "down"

### ISSUE THREAD

**Issue by andyautida14** [testcontainers/testcontainers-go#644]
### Proposal

When calling the `Down()` method of the `LocalDockerCompose` created through `NewLocalDockerCompose()`, volumes created when "upping" the instance are deleted through the `--volumes` option:

https://github.com/testcontainers/testcontainers-go/blob/20df64ea3d8b80668604487e8aff3bfb0e6da2ea/compose_local.go#L84

It would be nice to have that behavior on `ComposeStack.Down()` created through `NewDockerCompose()` as well. I believe  this can be easily achieved by adding `Volumes: true` on the following line:

https://github.com/testcontainers/testcontainers-go/blob/20df64ea3d8b80668604487e8aff3bfb0e6da2ea/compose_api.go#L158

BTW, I thank all the contributors of this awesome library. It's been really useful to me.

**Comment by mdelapenya** [comment]
Would you mind contributing it? I think it would be simple to review indeed
