### ISSUE TITLE
[Enhancement]: Move compose code to a separate Go module

### ISSUE THREAD

**Issue by mdelapenya** [testcontainers/testcontainers-go#646]
### Proposal

I think moving compose files to their own module would simplify the dependency tree for testcontainer-go.

Users of compose will have to deal with the transitive dependencies hack that we currently have at the main module, caused by Compose for Go, removing them from the main.

@baez90 wdyt?

**Comment by baez90** [comment]
I like the idea! Also I'm sorry that docker-compose refactoring caused so much pain so far but moving it to an extra module makes sense and keeps the dependency tree sleek for the main module, which is a very good thing!
