### ISSUE TITLE
[Bug]: Ryuk kills itself before removing networks, volumes and images

### ISSUE THREAD

**Issue by rzajac** [testcontainers/testcontainers-go#698]
### Testcontainers version

v0.16.0

### Using the latest Testcontainers version?

Yes

### Host OS

Linux

### Host arch

x86

### Go version

1.19

### Docker version

```shell
Client: Docker Engine - Community
 Version:           20.10.14
 API version:       1.41
 Go version:        go1.16.15
 Git commit:        a224086
 Built:             Thu Mar 24 01:47:58 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.14
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.15
  Git commit:       87a90dc
  Built:            Thu Mar 24 01:45:50 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.11
  GitCommit:        3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc:
  Version:          1.0.3
  GitCommit:        v1.0.3-0-gf46b6ba
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Docker info

```shell
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.1-docker)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 12
  Running: 2
  Paused: 0
  Stopped: 10
 Images: 37
 Server Version: 20.10.14
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc version: v1.0.3-0-gf46b6ba
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.19.0-26-generic
 Operating System: Ubuntu 22.10
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 31.25GiB
 Name: thor
 ID: S4XQ:6LAR:AMRS:JRG5:FPSO:NXHA:AD7P:TEZF:Y6FQ:RQ6R:NB46:CUQ7
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### What happened?

Since reaper container gets the `org.testcontainers.golang.sessionId` label:

https://github.com/testcontainers/testcontainers-go/blob/71461a93b65a712ec1bf7e962f8932986ffa9b7f/reaper.go#L74-L77

```
docker container inspect -f '{{.Config.Labels}}' f4afaff6443e 
map[org.testcontainers.golang:true org.testcontainers.golang.reaper:true org.testcontainers.golang.sessionId:9f7e7a47-db4b-4e8b-b1b5-7510e230a1db]
```
When the cleanup code is not run, because of panic for example, the reaper will trigger purging but doing so it will remove itself not getting to the networks, volumes and images. See ryuk code:

https://github.com/testcontainers/moby-ryuk/blob/8f512d37699cb6e5a3b28f2433c2b3b894a78e5d/main.go#L191-L240

The behavior may be seen looking at ryuk container logs as well:

```
2022/12/16 17:23:47 Pinging Docker...
2022/12/16 17:23:47 Docker daemon is available!
2022/12/16 17:23:47 Starting on port 8080...
2022/12/16 17:23:47 Started!
2022/12/16 17:23:47 New client connected: 172.17.0.1:49952
2022/12/16 17:23:47 EOF
2022/12/16 17:23:47 Client disconnected: 172.17.0.1:49952
2022/12/16 17:23:47 New client connected: 172.17.0.1:49966
2022/12/16 17:23:51 Adding {"label":{"org.testcontainers.golang.sessionId=edabcbdf-613d-4463-a04f-8cffbb351112":true,"org.testcontainers.golang=true":true}}
2022/12/16 17:23:51 New client connected: 172.17.0.1:49968
2022/12/16 17:23:51 EOF
2022/12/16 17:23:51 Client disconnected: 172.17.0.1:49968
2022/12/16 17:24:13 EOF
2022/12/16 17:24:13 Client disconnected: 172.17.0.1:49966
2022/12/16 17:24:23 Timed out waiting for re-connection
2022/12/16 17:24:23 Deleting {"label":{"org.testcontainers.golang.sessionId=edabcbdf-613d-4463-a04f-8cffbb351112":true,"org.testcontainers.golang=true":true}}
```

The final line 

https://github.com/testcontainers/moby-ryuk/blob/8f512d37699cb6e5a3b28f2433c2b3b894a78e5d/main.go#L61

is never displayed.

**Comment by HofmeisterAn** [comment]
> Since reaper container gets the org.testcontainers.golang.sessionId label:

.NET creates and starts the Resource Reaper with `AutoRemove=true` and without session ID label. Probably we need the same implementation in Go. At the same time we should think to address the issue in https://github.com/testcontainers/moby-ryuk too.

**Comment by matthewmcnew** [comment]
I created a [temporary workaround ryuk image](https://github.com/matthewmcnew/moby-ryuk/commit/882cbf00fccee1e1b55313eaf04ec0a8ab5f86ab) that prevents ryuk from deleting itself.

Is there a more general way to identify the ryuk container?

**Comment by kiview** [comment]
@matthewmcnew As a first idea, we could add a generic label to the Ryuk image and have the Ryuk implementation ignore containers with this label. This would limit this change and behavior to Ryuk and the downstream language projects would not need to take care of it as well.

**Comment by HofmeisterAn** [comment]
> As a first idea, we could add a generic label to the Ryuk image and have the Ryuk implementation ignore containers with this label.

As long as no one sets the hostname property, we can use the hostname to identify the container too (the hostname equals the container id). Although, the label sounds more reliable.

**Comment by matthewmcnew** [comment]
I liked the idea of a Ryuk specific label. I updated my branch and PR'd that to Ryuk: https://github.com/testcontainers/moby-ryuk/pull/53.
