### ISSUE TITLE
Is it possible to attach created containers to a specific docker network?

### ISSUE THREAD

**Issue by mdelapenya** [testcontainers/testcontainers-go#73]
The use case would be creating a dedicated network for testing/local dev, so it's possible to attach created containers to it.

At this moment, the NetworkingConfig is passed as `nil`.

If you consider implementing it, I'd be glad to contribute it :)

**Comment by mdelapenya** [comment]
Meanwhile I get feedback from this, I continued attaching containers to the default `bridge` Docker network.

While it could be enough, I consider it be very convenient if the API exposed the `inspectContainer` method, so any client code could use whatever information they need, instead of using just the existing`Host(), Name(), Ports()`, etc.

Wdyt?

**Comment by gianarb** [comment]
I think we can do that, it doesn't need to be part of the Container interface because I would like to keep that interface easy to implement eventually with containerd or some other provider.

**Comment by mdelapenya** [comment]
Merged, thanks!

![image](https://media.giphy.com/media/D0WOL0ogZIoG4/giphy.gif)
