### ISSUE TITLE
Define Cmd as Slice of Strings

### ISSUE THREAD

**Issue by ClaytonNorthey92** [testcontainers/testcontainers-go#86]
**Describe the bug**
Not a bug, a suggestion.
When creating a `ContainerRequest`, we give the `Cmd` attribute a `string` type.  Then we [parse it to make it a slice of strings](https://github.com/testcontainers/testcontainers-go/blob/master/docker.go#L252)

Would it be a better idea to define the [Cmd attribute in the ContainerRequest struct](https://github.com/testcontainers/testcontainers-go/blob/master/container.go#L47) as a slice of strings (`[]string`)?

The implicit parsing (splitting) is not clear to a user of the project, I think it would be good to be explicit here.

**To Reproduce**
Intentionally leaving blank, not a bug, a suggested change.

**Expected behavior**
```
type ContainerRequest struct {
	Image        string
	Env          map[string]string
	ExposedPorts []string // allow specifying protocol info
	Cmd          []string
	Labels       map[string]string
	BindMounts   map[string]string
	RegistryCred string
	WaitingFor   wait.Strategy
	Name         string // for specifying container name
	Privileged   bool   // for starting privileged container

	SkipReaper bool // indicates whether we skip setting up a reaper for this
}
```

**Comment by gianarb** [comment]
Yes! I like it! I think we can do a bc-break here and to change it as slice of string. @ClaytonNorthey92 do you mind to open a PR?! 

Thanks

**Comment by ClaytonNorthey92** [comment]
@gianarb awesome!  Yes I can open a PR for this ASAP!
