### ISSUE TITLE
[Enhancement]: allow manual exposed port mapping

### ISSUE THREAD

**Issue by TeddyDD** [testcontainers/testcontainers-go#949]
### Proposal

The user should be able to manually map the exposed container ports to the host ports.

Use case: Kafka and Redpanda - they need to have external port passed as argument. The current workaround from testcontainers-java is overcomplicated and in case of images without shell - does not work. On the other hand, manually asking the system for the next available port is trivial.

**Comment by mmadraimov92** [comment]
It is possible to manually set host ports to map to container exposed ports by providing `ExposedPorts` string in the format `ip:host_port:container_port/proto`, similar to `docker run -p` https://docs.docker.com/engine/reference/commandline/run/#publish

ex:
```go
req := testcontainers.ContainerRequest{
	Image:        "postgres:15-alpine",
	ExposedPorts: []string{"1337:5432"},
        ...
}
```

**Comment by mdelapenya** [comment]
I think we can close this one, as the suggestion from @mmadraimov92 is the usual way to manually force a fixed port on a container.

Thanks!
