### ISSUE TITLE
[Bug]: container is not started with panic /bin/sh command not executable: failed to start container

### ISSUE THREAD

**Issue by hannagm2016** [testcontainers/testcontainers-go#951]
### Testcontainers version

0.19.0

### Using the latest Testcontainers version?

Yes

### Host OS

Linux

### Host arch

x.86

### Go version

1.18

### Docker version

```shell
-
```

### Docker info

```shell
-
```

### What happened?

Creating a generic container with parameters failed after lates updates.
Parameters for creating GenericContainer are the same (5 days ago it worked fine), but action started to fail with "panic: /bin/sh command not executable: failed to start container"

I tried to add "SkipReaper:   true" to ContainerRequest, but it didn't help

### Relevant log output

```shell
Starting container id: ... image: percona/percona-server:8.0
Waiting for container id ... image: percona/percona-server:8.0
panic: /bin/sh command not executable: failed to start container
```

**Comment by mdelapenya** [comment]
Could you share the container request so that we can have a better understanding of the reproduction steps?

Apart from that, could you `docker run` the same image and try to exec into the container to run `sh`? I'd like to know whether the percona image does have it or not

**Comment by hannagm2016** [comment]
@mdelapenya, please check request
`testcontainers.ContainerRequest{
   Env: map[string]string{
      "MYSQL_USER":                 "core",
      "MYSQL_DATABASE":             "core",
      "MYSQL_PASSWORD":             "core",
      "MYSQL_ALLOW_EMPTY_PASSWORD": "yes",
   },
   Name:         "mysqltest",
   Image:        "percona/percona-server:8.0",
   ExposedPorts: []string{"3306/tcp"},
   WaitingFor:   wait.ForListeningPort("3306"),
   SkipReaper:   true,
}`

P.S. also I figured out that this error appears in case  ```
exitCode == 126 {
			return errors.New("/bin/sh command not executable")
		}
```

**Comment by hannagm2016** [comment]
actually, I don't know
just used mysql image instead percona
